### ISSUE TITLE
Startup error when disabling dashboard

### ISSUE THREAD

**Issue by aperum** [NTBBloodbath/doom-nvim#100]
**Description**
When dashboard is disabled in doomrc init.lua still tries to load it because it only tests for the existence of packer_compiled.lua which also exists if the dashboard is disabled.

**Fix**
My fix was to check the packer_plugins table if dashboard exists. 

```
diff --git a/init.lua b/init.lua
index 51214ce..9d97dcd 100644
--- a/init.lua
+++ b/init.lua
@@ -36,16 +36,11 @@ async = vim.loop.new_async(vim.schedule_wrap(function()
                -- Load Doom core
                require('doom.core')

-               -- If the dashboard plugin is already installed and the packer_compiled.lua
-               -- file exists so we can make sure that the dashboard have been loaded
-               local compiled_plugins_path = vim.fn.expand(
-                       '$HOME/.config/doom-nvim/plugin/packer_compiled.lua'
-               )
-               if vim.fn.filereadable(compiled_plugins_path) > 0 then
-                       -- If the current buffer name is empty then trigger Dashboard
+               if packer_plugins['dashboard-nvim'] then
+                 -- If the current buffer name is empty then trigger Dashboard
                        if vim.api.nvim_buf_get_name(0):len() == 0 then
-                               vim.cmd('Dashboard')
-                       end
+                   vim.cmd('Dashboard')
+                 end
                end

                vim.opt.shadafile = ''
```

**Local diff**
[DiffGist](https://gist.github.com/aperum/6b865edcc3937eac7bce996344bc16b6)

**Comment by NTBBloodbath** [comment]
Hey man, sorry for the late reply I was sleeping haha

Thank you so much for breaking doom-nvim and reporting it, that's how we can make this setup more versatile and stable, I'll try to fix it as soon as possible (my net is constantly dying today) :)

**Comment by NTBBloodbath** [comment]
Should be fixed now, please update and feel free to re-open this issue if you're still facing this issue.

Regards
