### ISSUE TITLE
Mac M1 - haskell module startup err / tree sitter install fails

### ISSUE THREAD

**Issue by molleweide** [NTBBloodbath/doom-nvim#111]
Hi guys,

I just got my new macbook air m1 silicone and it seems that I get the exact same
error when starting neovim after having setup all of my configs as in this issue
that I reported earlier:

https://github.com/NTBBloodbath/doom-nvim/issues/70

I will report back if I figure out why.

**Comment by NTBBloodbath** [comment]
Hey, have you seen the haskell tree-sitter parser repository issues? Don't know but maybe _and hopefully_ there will be an issue about installing the parser in a macbook M1

**Comment by molleweide** [comment]
Yo sorry for not having replied in acouple of days. 
Yes I am working on this again now. I have to go over the links that I used last time. This will probably not be a big deal to solve :P

**Comment by molleweide** [comment]
i belive I fixed the problem. I submitted a tiny PR to tree-sitter-haskell.
https://github.com/tree-sitter/tree-sitter-haskell/pull/46/commits/710dcf8b381a7cbcfd327536516e8eecda6136d6
