### ISSUE TITLE
Feature request: replace nvim-compe

### ISSUE THREAD

**Issue by NTBBloodbath** [NTBBloodbath/doom-nvim#112]
At first I thought that doom needed to stay in compe for a while because cmp was still very young and was still suffering a ton of daily breaking changes so I didn't wanted to migrate yet as other setups did because our active contributors amount is almost non-existent and I don't have the sufficient time to fix external stuff every day haha.

But I think that cmp ecosystem is maturing and no longer undergoing constant breaking changes, so we can finally make the jump to it.

**Comment by abzcoding** [comment]
we can close this 😈
