### ISSUE TITLE
anyone know how to include hiddn files/dirs in telescope?

### ISSUE THREAD

**Issue by molleweide** [NTBBloodbath/doom-nvim#116]
Hey guys,

How would one include hidden files in telescope results.
I tried adding "--hidden" flag to the find_command table but that didn't seem to work.
I think it would be nice to have an option in doomrc to toggle this so that one can browse
dotfiles and configs. Does this make sense?

**Comment by abzcoding** [comment]
i mean you can probably map a command to it yourself, in your doom_config.lua
```lua
  mappings = {
    {
      "n",
      "sth", -- change this to a proper key
      ":Telescope find_files find_command=rg,--ignore,--hidden,--files prompt_prefix=🔍",
      { silent = true },
    },
  },
```
