### ISSUE TITLE
Looking for contributors

### ISSUE THREAD

**Issue by NTBBloodbath** [NTBBloodbath/doom-nvim#117]
Hey, so as the title says I'm looking for some contributors to help me to maintain Doom Nvim. I really love this project, spent a ton of my time on it and this is the Neovim framework that I always dreamed. A highly customizable and extensible setup that can fit everyone needs with just a few modifications because not everyone needs the same plugins and configurations.

Sadly I don't have the enough time to maintain Doom 24/7 as before, I now have other projects too (all of them related to Neovim), also a job and the university admission exams are very near so I need to study if I want to pass them (I suck at maths) haha.

And now that you know this, let's see what are you gonna do as a Doom contributor!

#### What will you do as a contributor?

You will mainly help managing issues by helping other users to fix them and also help to fix the occasional plugins breaking changes (I really hate them haha). You can also add new features to Doom Nvim and help us all to have a better coding experience!

On my way I can help you in everything you could need to know about how Doom Nvim works internally, teach you some Lua stuff if you want to, etc. I will be glad to help you in your task of help maintaining Doom :)

---

Please let me know if you're interested on being a Doom Nvim contributor and if you have questions so I can help you!

Regards

**Comment by NTBBloodbath** [comment]
Hi, thanks for your interest in this project! :)

I'm really excited about your ideas. You can reach me on Discord (there's a badge in Doom's readme that links to the recently made Doom server) and Telegram, I would also say Reddit but I'm not very active on this one haha.

Regards

**Comment by caligian** [comment]
Hi, I can provide utility functions to provide an emacs-like keybinding and Event-hooking experience.

I also have a basic lua REPL plugin written that works for any language as long as it's got an REPL of its own. Also, it supports vscode-style window splitting (vsp) also for terminal usage. Additionally, users can send text from their buffers to either commandline or buffer's associated REPL!

Additionally, I have buffer-running functions for quick testing too. 

I wish to add these to make it a better experience and maintain the same.

**Comment by NTBBloodbath** [comment]
Hey, just saw the discussion you've made (#274 if someone else wants to take a look) and I completely agree with what you've said on it :)

Also I'm really loving what you've said here and I really appreciate your interest on this project. Any contribution is welcome :)

**Comment by caligian** [comment]
https://www.github.com/caligian/nvimrc

You can check out lua/funcs.lua and lua/kbd.lua
