### ISSUE TITLE
Disabling which-key let doomnvim configuration to fail

### ISSUE THREAD

**Issue by mcctuxic** [NTBBloodbath/doom-nvim#124]
Hi,

in doom_config.lua there is written:

```
    keybinds_modules = {
      -- Core doom keybindings
      core = true,
      -- Movement keybindings, jump between your windows, buffers and code
      movement = true,
      -- Leader keybindings, a bunch of useful keybindings managed by space key
      -- WARNING: disabling this will break which-key plugin if the plugin is enabled
      leader = true,
      -- Completion and snippets keybindings
      completion = true,
    },

```
The warning let one disable which-key in doom_modules.lua. When nvim is started, which-key will be removed. Next start this message appears: "Check you config for correctness!" which is the second half of a two line message and which first part is not displayed and contains supposedly the information, what has gone wrong. Enabling which-key again fixes that problem...but it
is in contradiction to what the Warning implies.

**Comment by NTBBloodbath** [comment]
Hey, can you please delete the which-key plugin again and send the output of `:mess` when the error is raised?

I think it's probably that packer isn't running `:PackerCompile` as it should so the `plugin/packer_compiled.lua` could still have the which-key plugin entry :thinking:

**Comment by mcctuxic** [comment]
Hey,
Here are the results: I removed which-key from the config and started nvim. I got a message about removing which-key (1st.png), to which I agreed. Nothing more was displayed then. I run PackerSync then and ended nvim. After restarting nvim I got the message "Check your configuration for correctness"-message and gave the command ":mess" which displayed the message as given in 2nd.png. Then I did a PackerCompile, ended nvim and restarted nvim and got the "Check your configuration...."-message again. 3rd.png shows the message I got after submitting ":mess" again.
![1st](https://user-images.githubusercontent.com/30279786/134275178-23ebe5af-875b-4d3b-a333-b441198bcfbc.jpg)
![2nd](https://user-images.githubusercontent.com/30279786/134275203-95e03ec4-23f2-4013-9209-743adae1cc78.jpg)
![3rd](https://user-images.githubusercontent.com/30279786/134275217-90e88a61-799c-4a7b-8bb1-c6b563998841.jpg)

**Comment by osamuaoki** [comment]
Did you type Y to the questions?

**Comment by mcctuxic** [comment]
Yes, I did.
Yes, I run PackerCompile afterwards.
Yes, I restarted nvim after running PackerCompile.
Then I got an error message. After syncing with the repo
this morning the error message says:
	Error in packer_compiled: ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:13: Err
	or: attempted to load which-key.nvim which is not present in plugins table!

Why is a plugin tried to be loaded after removing it?
or
Why is it possible to remove a plugin, which makes doom-nvim to fail,
if not there?

**Comment by NTBBloodbath** [comment]
Hi, I think I caught what the error is. I was wrongly assuming that which-key is present and trying to load it in our init file. I'll fix it asap.

Regards

**Comment by NTBBloodbath** [comment]
Please update Doom and let me know if this still happens

**Comment by mcctuxic** [comment]
Fixed! Thank you!
