### ISSUE TITLE
VIM HELP "LOCAL ADDITION"

### ISSUE THREAD

**Issue by osamuaoki** [NTBBloodbath/doom-nvim#126]
Hi,

Thank you for your careful coding efforts.  This helped me to set up in new lazy loading way.

I am new to this lazy loading but my old style mentality makes me feel a bit odd.  Whenever I add a package with `doc/` directory, I expected to get it listed in **LOCAL ADDITION** for my easy access.  But I don't see many of them. 

I cross checked current situation by checking `.../site/**/{opt,start}` and `LOCAL ADDITIONS`.  (See below for actual data)

* `nvim-tree.lua` is not in included in `tagfiles` (active for sure module missing in `taglist`)
* many upstream doesn't have doc/ directory and not in LOCAL ADDITIONS: (No problem)
* many listed below with (???) are not showing up in LOCAL ADDITIONS even though they have `doc/` directory.
* There are many entries LOCAL ADDITIONS even for event triggered  packages like `gitsigns` so the root cause is not always be the lazy loading.
* tags listed in tagfiles without entry in `LOCAL ADDITIONS` can be searched as expected.

What exactly is happening and how to get this in the sane condition
If coding to address is not easy from DOOM-NVIM, I think a short pointer reference in DOOM-NVIM to pertinent documentation may be one way. 

One way to work around this odd situation is to copy the `doc/` content file to `$HOME/.config/nvim/doc` and `:heloptags $HOME/.config/nvim/doc` in nvim as described in `:h add-local-help`.  This isn't elegant solution but works.  I think, at worst, config script may be updated to copy pertinent files and run helptags after PackerCompile automatically, I guess..  (But before doing it, it may be good idea to identify the root cause and situation of this missing entry.)

## echo tagfiles() output -- formatted
```
doom_nvim.txt --    /home/osamu/.config/nvim/doc/tags'
???                 /home/osamu/.local/share/nvim/site/pack/packer/opt/DAPInstall.nvim/doc/tags'
???                 /home/osamu/.local/share/nvim/site/pack/packer/opt/LuaSnip/doc/tags'
???                 /home/osamu/.local/share/nvim/site/pack/packer/opt/TrueZen.nvim/doc/tags'
???                 /home/osamu/.local/share/nvim/site/pack/packer/opt/bufferline.nvim/doc/tags'
???                 /home/osamu/.local/share/nvim/site/pack/packer/opt/format.nvim/doc/tags'
gitsigns.txt   --   /home/osamu/.local/share/nvim/site/pack/packer/opt/gitsigns.nvim/doc/tags'
???                 /home/osamu/.local/share/nvim/site/pack/packer/opt/indent-blankline.nvim/doc/tags'
???                 /home/osamu/.local/share/nvim/site/pack/packer/opt/neorg/doc/tags'
compe.txt      --   /home/osamu/.local/share/nvim/site/pack/packer/opt/nvim-compe/doc/tags'
???                 /home/osamu/.local/share/nvim/site/pack/packer/opt/nvim-dap/doc/tags'
???                 /home/osamu/.local/share/nvim/site/pack/packer/opt/nvim-lspconfig/doc/tags'
nvim-treesitter --  /home/osamu/.local/share/nvim/site/pack/packer/opt/nvim-treesitter/doc/tags'
???                 /home/osamu/.local/share/nvim/site/pack/packer/opt/packer.nvim/doc/tags'
???                 /home/osamu/.local/share/nvim/site/pack/packer/opt/vim-qlist/doc/tags'
qlist.txt      --   /home/osamu/.local/share/nvim/site/pack/packer/opt/vim-spell-under/doc/tags'
packer         --   /home/osamu/.local/share/nvim/site/pack/packer/start/aniseed/doc/tags'
dashboard.txt  --   /home/osamu/.local/share/nvim/site/pack/packer/start/dashboard-nvim/doc/tags'
editorconfig.txt -- /home/osamu/.local/share/nvim/site/pack/packer/start/editorconfig-vim/doc/tags'
???                 /usr/share/nvim/runtime/doc/tags'
matchit.txt    --   /usr/share/nvim/runtime/pack/dist/opt/matchit/doc/tags'
```

**Comment by osamuaoki** [comment]
I realize that if `nvim-tree.lua` is active by opening it on the left side and if the cursor is in help window, tagfiles() contains its tag path.  Since delayed loading by command is used rtp is active only when it is activated.  Since tagfiles() is usually `[]`, this is set by starting `:help`.  So this makes sense.

Considering complicated things needed to address this problem, simplest thing may be make a symlink from `~/.config/nvim/doc/foo.txt` to target doc `.../opt/packagename/doc/foo.txt` and `:helptags ...` may be the realistic solution.

Maybe worth motioning in documentation.

**Comment by NTBBloodbath** [comment]
Hi, thanks for such words!

Yeah this is an annoying issue even to me. It seems that it's the default Neovim behavior since the plugins manager that Doom is using (`packer.nvim`) uses `packadd` to load optional plugins and according to `:h packadd` it searches the requested plugin name and then loads all the found plugin files, including `doc/` directory afaik.

The solution that you've proposed seems to be the correct one and since making symlinks can have a "high" cost if they're a ton we could use [luv](https://github.com/luvit/luv) _which is embedded in Neovim_ instead of calling Vimscript functions. [Here](https://github.com/luvit/luv/blob/master/docs.md) are the docs, and the way to call luv functions in Neovim is by using `vim.loop`, e.g.

```lua
--- uv.fs_symlink(path, new_path, [flags], [callback])
vim.loop.fs_symlink(".../opt/packagename/doc/foo.txt", ".../nvim/doc/foo.txt")
```

Also feel free to ask me if you have any question about how luv works if you want to work on it.

**Comment by osamuaoki** [comment]
If we automatically add the symlink, there is a fairly good chance to cause duplicate error.  You never know if a package is loaded or not.  So I think reasonable thing to do is document it.

https://github.com/NTBBloodbath/doom-nvim/pull/132/commits/0d34c6b8478626099d401bb3c8b175256048117f

**Comment by osamuaoki** [comment]
I think this is addressed in documentation doc/doom_nvim.norg now.

7ca9451 ("doc: more in doom_nvim.norg", 2021-09-30)

So let's close this ;-)  Thanks.
