### ISSUE TITLE
shortmess=aTI (no intro screen) has no effect

### ISSUE THREAD

**Issue by mcctuxic** [NTBBloodbath/doom-nvim#129]
I have dashboard disabled.
A bare bone nvim (and vim) displays a "splash screen", which looks like text in a buffer whith version information
and a little help.
This "splash screen" can be disabled by setting shortmess=I (capital i) according to the :h shortmess.
shortmess is global. Setting shortmess=I in the section for global variables near the end of doom_config.lua has no effect.
Using "set shortmess=I" as a command in the according section in doom_config.lua has no effect.
The "splash/intro message" is still briefly displayed.

**Comment by osamuaoki** [comment]
How did you disable dashboard? 

If you disabled by packer, you need to run :PackerCompile?

**Comment by mcctuxic** [comment]
Yes, I disabled Dashboard via doom_modules.lua.
Yes, I did run PackerCompile afterwards.
Running PackerCompile automatically everytime, 
when the message "Delete XYZ Y/N" pops up after disabling 
a module and is answered by "yes" would help in those cases.

**Comment by NTBBloodbath** [comment]
Hi, can you please send the output of `set shortmess?` while you're on intro screen?

**Comment by mcctuxic** [comment]
Not really...it is shown briefly and is replaced by the colorscheme
afterwards - a process I cannot stop.
This may be a result of the general delay in loading all the doom stuff.

**Comment by NTBBloodbath** [comment]
Hmm right, this supposes a problem for us. Can you please add this in your `init.lua` file before the `vim.defer_fn` function? After this restart Neovim and send the output (do `:messages` if you can't see it).

```lua
print(vim.inspect(vim.opt.shortmess:get()))
```

In my head this should be executed during the default neovim intro screen before being replaced by the colorscheme. See if `I` is in the table.

**Comment by mcctuxic** [comment]
I added the command and it prints:

  F = true,
  O = true,
  T = true,
  f = true,
  i = true,
  l = true,
  n = true,
  o = true,
  t = true,
  x = true
}

**Comment by NTBBloodbath** [comment]
Hmm alright, did u saw the edit on my comment? As I can see you're replying from mail and I don't know if GitHub re-sends the messages when they were edited haha.

As a tl;dr you will need to add this at top of your `init.lua` file to avoid this strange behavior caused by the loading order and speed of things.

```lua
vim.opt.shortmess:append("I")
```
