### ISSUE TITLE
Startup time is out of display

### ISSUE THREAD

**Issue by osamuaoki** [NTBBloodbath/doom-nvim#135]
Unless I remove 1 blank line from DOOM LOGO string, startup time is out of screen for me.  I don't want to miss 22 ms ;-)

I use HACK 14 on LAPTOP with  1920x1080 pixels LCD.  Here is after removing one line:
![DOOM-less-1-line](https://user-images.githubusercontent.com/7339387/134798532-3bfbbfbe-4997-4cfa-b56a-19d6b2b68d89.png)

**Comment by NTBBloodbath** [comment]
Hi, can you please create a PR with this change? I think it would be useful for others too :)
