### ISSUE TITLE
<leade>db broken after showing which-key window

### ISSUE THREAD

**Issue by osamuaoki** [NTBBloodbath/doom-nvim#145]
Thanks for the recent updates especially loading colorscheme early.  This makes starting of doom-nvim looks much nicer without flickering start.

I have not nailed down when this started, but within 1 week or so, `<leade>db` became broken  after showing which-key window as I found out today.  I tested on the latest unmodified `develop` branch.

 b1bfa6c ("chore: remove non-needed sessions dir", 2021-09-29)

Since Telescope had rather big updates recently, mapper may need to be updated or doom-nvim may need to accommodate this update. mapper is the same for over a month.

Here is the output after the key strokes.  Maybe pre-load telescope for mapper.

```
packer.nvim: Error running config for telescope.nvim: ...er/opt/telescope.nvim/lua/telescope/_extensions/init.lua:12: This extension doesn't exist or is not installed: mapper
module 'telescope._extensions.mapper' not found:
^Ino field package.preload['telescope._extensions.mapper']
^Ino file './telescope/_extensions/mapper.lua'
^Ino file '/usr/share/luajit-2.1.0-beta3/telescope/_extensions/mapper.lua'
^Ino file '/usr/local/share/lua/5.1/telescope/_extensions/mapper.lua'
^Ino file '/usr/local/share/lua/5.1/telescope/_extensions/mapper/init.lua'
^Ino file '/usr/share/lua/5.1/telescope/_extensions/mapper.lua'
^Ino file '/usr/share/lua/5.1/telescope/_extensions/mapper/init.lua'
^Ino file '/home/osamu/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/telescope/_extensions/mapper.lua'
^Ino file '/home/osamu/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/telescope/_extensions/mapper/init.lua'
^Ino file '/home/osamu/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/telescope/_extensions/mapper.lua'
^Ino file '/home/osamu/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/telescope/_extensions/mapper/init.lua'
^Ino file './telescope/_extensions/mapper.so'
^Ino file '/usr/local/lib/lua/5.1/telescope/_extensions/mapper.so'
^Ino file '/usr/lib/x86_64-linux-gnu/lua/5.1/telescope/_extensions/mapper.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'
^Ino file '/home/osamu/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/telescope/_extensions/mapper.so'
^Ino file './telescope.so'
^Ino file '/usr/local/lib/lua/5.1/telescope.so'
^Ino file '/usr/lib/x86_64-linux-gnu/lua/5.1/telescope.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'
Press ENTER or type command to continue


```

**Comment by osamuaoki** [comment]
I don't see problem with 68e1b00 ("fix(gitsigns) match new variable name", 2021-09-26) (on develop)
So something was recently broken in doom-nvim

**Comment by osamuaoki** [comment]
This  57ab1c2 ("refact(init): do not disable syntax highlighting on launch, closes #131", 2021-09-29) commit broke this.

**Comment by NTBBloodbath** [comment]
Hi, thank you so much for pointing to the commits!

Maybe this could be a lazy-loading issue since I haven't touched the telescope stuff nor its extensions.

Does it load when you run `:Telescope` before?

**Comment by NTBBloodbath** [comment]
It's working on my side again, feel free to reopen this issue if you're still facing this error

**Comment by osamuaoki** [comment]
Yes.  It works for me too.
