### ISSUE TITLE
Consider switching to williamboman/nvim-lsp-installer for Windows support, and more supported LSPs.

### ISSUE THREAD

**Issue by Elabajaba** [NTBBloodbath/doom-nvim#166]
The current kabouzeid/nvim-lspinstall doesn't support Windows (hardcoded /usr/bin/env bash, and doesn't actually install the LSP on Windows. There was a PR for Windows support, but it died). williamboman/nvim-lsp-installer supports Windows, and seems to contain every LSP that nvim-lspinstall does, and more (based on comparing their respective LSP support tables in their READMEs).

https://github.com/williamboman/nvim-lsp-installer

**Comment by NTBBloodbath** [comment]
Hey, thank you per recommending this one, looks amazing :)

However I was thinking about using [MordechaiHadad/nvim-lspmanager](https://github.com/MordechaiHadad/nvim-lspmanager) in a near future, this one works asynchronously, has support for updating servers and has full support for Windows too, the maintainer uses Windows as his main system.

I'll be investigating both, nvim-lsp-installer seems to be more mature actually, however I'm really interested in async jobs and commands to update language servers.

Regards :)

**Comment by Elabajaba** [comment]
An issue I see with nvim-lspmanager is the lack of LSPs compared to nvim-lspinstall (current) or nvim-lsp-installer (my suggestion). Async and the ability to update servers would be very nice however.
