### ISSUE TITLE
Personalized doomrc

### ISSUE THREAD

**Issue by bketelsen** [NTBBloodbath/doom-nvim#18]
Great project! I was looking for a way to keep my doomrc outside of the git tree so I can update doom-nvim without overwriting my doomrc changes. Is that possible now?

**Comment by NTBBloodbath** [comment]
Hey, thank you!

>  I was looking for a way to keep my doomrc outside of the git tree so I can update doom-nvim without overwriting my doomrc changes. Is that possible now?

Yeah, it's possible. doing `<leader>du` will call the `:DoomUpdate` command which will basically execute the following git commands:
- `stash` - save your local changes
- `pull` - pull upstream changes
- `stash pop` - restore your stashed local changes

But if you're using the development branch I've changed that behavior to use a patch instead.
- `diff doomrc > doomrc_bak.patch` - saves your doomrc changes in a patch file
- `restore doomrc` - restores the doomrc to defaults
- `stash -u` - save your local changes, including the untracked files
- `pull` - pull upstream changes
- `stash pop` - restore your stashed local changes
- `apply doomrc_bak.patch` - apply your doomrc changes again

Note that both methods can have problems if the remote files had much changes and the merging isn't possible. In that case, you'll need to fix it manually (was thinking about adding some command like `:DoomRepair` for this).

In case you have merging problems after trying to update doom-nvim and you can't restore the stashed changes, you can run the following git commands in your doom-nvim path:

```sh
git reset
git stash drop
```

**Comment by bketelsen** [comment]
Brilliant thank you

**Comment by will** [comment]
To expand on this a little, what is the best approach to adding customizations that would minimize merge conflicts on update? I'm not looking to do a lot—just a few keybindings and options for plugins and stuff.

**Comment by NTBBloodbath** [comment]
> what is the best approach to adding customizations that would minimize merge conflicts on update?

I think the patch files are a good approach since they obviously just applies some patches to files and in that way, apply changes to some values.

However I think the merging conflicts depends more on my side. But anyways the settings of the plugins and the keybindings don't usually suffers changes so I don't see much problem with them.
