### ISSUE TITLE
error in lsp_signature not found 

### ISSUE THREAD

**Issue by Mremmalex** [NTBBloodbath/doom-nvim#19]
when i launch neovim after the install scrips, it shows error, that lsap_signature is not found and i still cant get it to work
![Screenshot from 2021-06-25 23-40-15](https://user-images.githubusercontent.com/40169444/123492047-43c90380-d610-11eb-8b41-41073a1a5f17.png)

**Comment by NTBBloodbath** [comment]
Hey, I have installed the stable branch and couldn't reproduce the error. Maybe the plugin was not downloaded properly?

**Comment by Mremmalex** [comment]
What should I do to resolve mine, re-install doom-vim or something

**Comment by NTBBloodbath** [comment]
Try running `:PackerSync` and then restarting Neovim after finishing. Lemme know if the issue persists!

**Comment by Mremmalex** [comment]
When I run any packer commad it returns an error, stating "error executing vim. schedule Lua callback: ... Ite/pack/packer/start/packer/display. Lua:152: invalid key 'noautocmd'"

**Comment by NTBBloodbath** [comment]
Oh, that means that you need to update your Neovim nightly version, see the first notice in packer's [README](https://github.com/wbthomason/packer.nvim#notices).

**Comment by Mremmalex** [comment]
![Screenshot from 2021-06-26 03-04-16](https://user-images.githubusercontent.com/40169444/123498945-ec845c80-d62a-11eb-8908-e282ff3a7f4a.png)

this is the version of neovim i'm on

**Comment by NTBBloodbath** [comment]
Have you updated it recently? If not, you must update it for packer to work properly :slightly_smiling_face:

**Comment by Mremmalex** [comment]
i updated it the error is gone, i had to build from source for it to work
