### ISSUE TITLE
problems when opening vim in a second doom clone instance

### ISSUE THREAD

**Issue by molleweide** [NTBBloodbath/doom-nvim#190]
1. I. cloned doom to a second location on my system
     in order to manually copy some stuff to a new branch
2. when opening vim in the root dir of the second instance vim acts very strange
     in the start up view.
3. However, if I open a lua file from the second instance in a subdir, eg. modules/init.lua, then
     there is no problems.

**Comment by connorgmeehan** [comment]
Can we get some more info on the specifics of this issue, is it still occuring?  I can't recreate this on macos with my doom-nvim worktree.

**Comment by NTBBloodbath** [comment]
> Can we get some more info on the specifics of this issue, is it still occuring?  I can't recreate this on macos with my doom-nvim worktree.

I think I fixed this but forgot to close the issue and reference the issue in the commit. Let's reopen this again later if someone is able to reproduce this.
