### ISSUE TITLE
moving lines gives error

### ISSUE THREAD

**Issue by molleweide** [NTBBloodbath/doom-nvim#191]
When trying to move lines with `<a-j/k>` it gives me:
```
  E5108: Error executing lua ...t/neorg/lua/neorg/modules/core/norg/manoeuvre/module.lua:65: attempt to call method 'next_named_sibling' (a nil value)
```

In lua files at the moment it seems to do nothing, hmmm.

**Comment by connorgmeehan** [comment]
@molleweide Now that you have neorg parser working can you go through these neorg related issues and check if any of these errors are still occuring?  If they're not can you close the issue?  I want to wrap as much up as we can before v3.2
