### ISSUE TITLE
Lspinstall not working.

### ISSUE THREAD

**Issue by GustavoPrietoP** [NTBBloodbath/doom-nvim#2]
whenever I type `:LspInstall` and hit tab to check the available language servers, I get this https://imgur.com/fBCMaKi (Sorry I can't send a picture here)

**Comment by NTBBloodbath** [comment]
Hi, did you enabled the lsp module in your `doomrc`? See [Enabling modules](https://github.com/NTBBloodbath/doom-nvim/blob/main/docs/modules.md#enabling-modules)

**Comment by GustavoPrietoP** [comment]
> Hi, did you enabled the lsp module in your `doomrc`? See [Enabling modules](https://github.com/NTBBloodbath/doom-nvim/blob/main/docs/modules.md#enabling-modules)

Hey! it seems like i missed this while reading the documentation, it works now :)
