### ISSUE TITLE
key map not working 

### ISSUE THREAD

**Issue by Mremmalex** [NTBBloodbath/doom-nvim#20]
they key map  functions is not working for my version, i'm running neovim 0.5, the keys maybe broken or something cause it dose not function

**Comment by NTBBloodbath** [comment]
Hey, can you provide more information about the error that you're facing? :slightly_smiling_face:

**Comment by Mremmalex** [comment]
the keymaps are not working for me, 
![Screenshot from 2021-06-26 02-54-04](https://user-images.githubusercontent.com/40169444/123498867-5fd99e80-d62a-11eb-9433-6a5449985a02.png)

when i do the (spc f f ) command all any other command like jk to go back to normal mode nothing happens for me, only C-c works for me nothing else

**Comment by Mremmalex** [comment]
working now after update
