### ISSUE TITLE
feature request: change working dir with telescope

### ISSUE THREAD

**Issue by molleweide** [NTBBloodbath/doom-nvim#200]
# doom feature request

## system info

- **OS**: Darwin
- **Neovim version**: 0.6.0 (dev)
- **Doom Nvim information**:
- **version**: 3.2.0-beta2
- **`doom_root` variable**: `/Users/hjalmarjakobsson/.config/doom-nvim`
- **`doom_configs_root` variable**: `/Users/hjalmarjakobsson/.config/doom-nvim`

## feat description

I want to be able to use telescope to change working
directories so that I can stay in the same nvim instance
all the time without having to jump in and out.

I use ranger file browser and telescope in order to browser
now with doom but as of now, none of these change working
dir.

As a side note I have been able to get ranger to switch working dir from
within but that script does not take effect in nvim.

## why this?

this would make life faster I think.

## details / implementation ideas

not sure yet. I am currently trying to get `Telescope-z`
extension to work. I see also that there are a bunch of interesting
telescope extensions that I want to check out later.
There is for example an extension for jumping betwen git projects that
I have to checkout.

# note

I tried creating a function that opens up a feature request
template that I used for creating this text. I will add this
to next PR. This is nice because this creates an empty buffer,
reads the template, and then also pastes in the system info
automatically. This is quite nice so that one can instantly
document new ideas.

**Comment by molleweide** [comment]
i have found and am testing a plug called `telescope-repo` which is really great for fuzzy searching $HOME for various kinds of scm's. I am talking to the maintainer currently about some issues on macos, but on linux it uses a cache with locatedb so that you can search your $HOME dir super fast.

**Comment by connorgmeehan** [comment]
This will be supported when the new module architecture drops.  I've added a `projects` module that allows you to switch to workspaces you've already edited with the `<leader>fp` command.  Keep track on discord, it should be ready for a beta/develop release soon (@NTBBloodbath has approved the PR).
