### ISSUE TITLE
Feature request: Missing themes from doom-themes

### ISSUE THREAD

**Issue by Viehzeug** [NTBBloodbath/doom-nvim#205]
Hey,

it seems some `doom-themes` can not be loaded.
Concretely it seems that only `.vim` themes in the `colors` folder are exposed while themes in the `lua` folder (e.g. https://github.com/GustavoPrietoP/doom-themes.nvim/tree/main/lua/doom-solarized) are not.
I assume a fix would be quite easy, but I don't know enough nvim-foo yet to do so. So any points welcome (i.e., specifically how would I interact with the lua themes and how are the exposed once `doom-themes` is loaded?).

Thanks for this project. Made emacs->nvim quite easy.

**Comment by molleweide** [comment]
Yea same problem for me

**Comment by NTBBloodbath** [comment]
Hey, sorry for the late reply.

This is an external plugin _not developed by me_ so this doesn't really depend on me to fix this. We could send some PRs to add missing colorschemes files (mainly in `colors/` directory) but nothing more ig.

**Comment by molleweide** [comment]
would it be possible to add other non doom-themes to the telescope-search list as well? If I get time then I would like to try to add some other themes as well.

**Comment by NTBBloodbath** [comment]
> would it be possible to add other non doom-themes to the telescope-search list as well? If I get time then I would like to try to add some other themes as well.

Yes, it is. Telescope search list looks for all the installed colorschemes, including the default ones :)

**Comment by molleweide** [comment]
That's great news. I have so many themes that I want to try out 😃

**Comment by connorgmeehan** [comment]
Closing due to resolved by `:Telescope colorscheme`
