### ISSUE TITLE
 Error while calling lua chunk:

### ISSUE THREAD

**Issue by Mremmalex** [NTBBloodbath/doom-nvim#21]
![Screenshot from 2021-06-26 03-08-49](https://user-images.githubusercontent.com/40169444/123499016-949a2580-d62b-11eb-99a9-8d5fe05d5ed9.png)

this error occurs after updating my neovim and install all the packages

**Comment by NTBBloodbath** [comment]
Hey, can you please paste the first 20 lines of the `~/.config/nvim/lua/doom/keybindings/init.lua` file?

**Comment by Mremmalex** [comment]
ok seems there was a line that is not commented had to comment it so the error is gone
