### ISSUE TITLE
Move from nvim-compe to nvim-cmp

### ISSUE THREAD

**Issue by remimimimi** [NTBBloodbath/doom-nvim#210]
[nvim-compe](https://github.com/hrsh7th/nvim-compe) readme says that repository is deprecated and we should use [nvim-cmp](https://github.com/hrsh7th/nvim-cmp)

**Comment by NTBBloodbath** [comment]
Hi, thanks for your interest in the project :)

We are already using cmp in development branch, hopefully the next release will be pushed soon to main. I'm going to close this because the feature already exists for the next release.

Regards
