### ISSUE TITLE
`vim-illuminate` error when Lsp is ON.

### ISSUE THREAD

**Issue by molleweide** [NTBBloodbath/doom-nvim#214]
# Doom error report

> Report date: 2021-11-01 15:42:52

## System and Doom Nvim information

- **OS**: Darwin
- **Neovim version**: 0.6.0 (dev)
- **Doom Nvim information**:
- **version**: 3.2.0-beta2
- **`doom_root` variable**: `/Users/hjalmarjakobsson/.config/doom-nvim`
- **`doom_configs_root` variable**: `/Users/hjalmarjakobsson/.config/doom-nvim`

### Error

``` vim
Error executing vim.schedule lua callback: ...m/site/pack/packer/opt/vim-illuminate/lua/illuminate.lua:119: attempt to index a nil value
```

I believe this is related to Lsp but I am quite a beginner when it comes
to that stuff. I also don't believe that I have changed any thing. 
I'll come back here and update if I realize I have messed something up myself.

**Comment by NTBBloodbath** [comment]
Hi,

This is an error caused by vim-illuminate (it doesn't happen to me btw) so this should be reported on the plugin repository IMO.

**Comment by molleweide** [comment]
Allright thanks ill close
