### ISSUE TITLE
does `gx` work for browsing links for anyone?

### ISSUE THREAD

**Issue by molleweide** [NTBBloodbath/doom-nvim#217]
For me it seems to only open a new window split of height 1 on the bottom

**Comment by connorgmeehan** [comment]
I can recreate this issue now, when opening a link using `gx` in a neorg buffer it doesn't work but using the `Enter` key it does. This is the resulting error message.  Is this your issue as well?  May have to open an issue on the neorg repo?
<img width="410" alt="Screen Shot 2021-11-17 at 8 56 49 am" src="https://user-images.githubusercontent.com/7402063/142072400-cc2ea33b-9ca8-4018-87c4-7d8991532d6e.png">

**Comment by molleweide** [comment]
no I don't think it is the same error if I recall. leaving this open for now.
