### ISSUE TITLE
lspInstall command not working after neovim update 

### ISSUE THREAD

**Issue by Mremmalex** [NTBBloodbath/doom-nvim#22]
![Screenshot from 2021-06-26 03-24-24](https://user-images.githubusercontent.com/40169444/123499338-d6c46680-d62d-11eb-87b7-f6bddfc406ce.png)

when i try to install an lsp it does not work, it returns the following error

**Comment by NTBBloodbath** [comment]
Hey can you run the following command? Let's check if the plugin is installed so we can debug it
`ls ~/.local/share/nvim/site/pack/packer/start/nvim-lspinstall`

**Comment by Mremmalex** [comment]
had to modify the doomrc file, for disabled plugins and packer install the necessary and now is working, thanks for your help so far, will sure buy you a coffee
