### ISSUE TITLE
user mappings don't load on startup

### ISSUE THREAD

**Issue by molleweide** [NTBBloodbath/doom-nvim#225]
I haven't learnt how to solve this myself yet.

What I notice is that I need to always run `<leader>dl` after startup in order for
my user bindings to take effect.

-------

> Report date: 2021-11-05 12:00:05

## System and Doom Nvim information

- **OS**: Darwin
- **Neovim version**: 0.6.0 (dev)
- **Doom Nvim information**:
- **version**: 3.2.0-beta2
- **`doom_root` variable**: `/Users/hjalmarjakobsson/.config/doom-nvim`
- **`doom_configs_root` variable**: `/Users/hjalmarjakobsson/.config/doom-nvim`

**Comment by NTBBloodbath** [comment]
Hi, are you sure that they aren't being loaded on startup? I cannot repro this :eyes:

**Comment by molleweide** [comment]
Hmm I guess I have to test this further on my sys but I am clearly having to run the command to load some of the mappings. I don't know atm if this is the case for all my personal mappings though. And this seems to have been the case when I was using master and also on dev currently, which I am using mostly.

I'll try to report back more on this later.

**Comment by xzebra** [comment]
I'm in develop branch and I'm having the same problem. In order to use mappings I have to `<leader>dl`.

This is my mappings config in case it helps:
```
    mappings = {
        {
            "n",
            "<leader>.",
            "<cmd>lua require('telescope.builtin').file_browser({ hidden=true, cwd = require'telescope.utils'.buffer_dir() })<CR>",
            {silent = true},
            "Editor",
            "find_files_here",
            "Find files here"
        }, 
        {'n', '<leader>gg', '<cmd>Neogit<CR>', {silent = true}, "Git", "magit", "Magit here"}
    },
```
# System and Doom Nvim information
**OS**: Manjaro
**Neovim version**: 0.6.0 (dev)
**Doom Nvim version**: 3.2.0-beta2

**Comment by molleweide** [comment]
Allright interesting to see that it is not only me then, hmmm.

**Comment by NTBBloodbath** [comment]
Hi, now I think I get what's happening here, thanks for sharing your mappings setup.

For `<leader>.` you could add noremap in the options at the moment, so our default one will not override yours because of loading order.

For `<leader>gg` you'll also need to add this to our which-key configs module (`lua/doom/modules/config/doom-whichkey.lua`). If which-key is enabled and the key isn't mapped internally then which-key will gracefully fail because it can't find the registered mapping in its internal database. Hopefully we will be able to solve this in next Doom versions by implementing [nest.nvim](https://github.com/LionC/nest.nvim) to manage our keybinds.

**Comment by molleweide** [comment]
I can just add here the my issue is pertaining to non leader mappings. 

However, I can also confirm that user mappings show
up in the leader menu if you add them to `doom-whichkey` module when I have added my own.

**Comment by xzebra** [comment]
Sorry to bother but none of the options solved the issue, as I still have to do `<leader>dl` to load the bindings.

> For `<leader>.` you could add noremap in the options at the moment, so our default one will not override yours because of loading order.

I tried with options `{ silent = true, noremap = true }` but no success.

> For `<leader>gg` you'll also need to add this to our which-key configs module (`lua/doom/modules/config/doom-whichkey.lua`). If which-key is enabled and the key isn't mapped internally then which-key will gracefully fail because it can't find the registered mapping in its internal database. Hopefully we will be able to solve this in next Doom versions by implementing [nest.nvim](https://github.com/LionC/nest.nvim) to manage our keybinds.

I changed the git section adding the first line for `<leader>gg`, but the issue remains.
```
    ["g"] = {
      name = "+git",
      ["g"] = { "Open Magit" },
      ["o"] = { "Open LazyGit" },
      ["l"] = { "Pull" },
      ["p"] = { "Push" },
      ...
    }
```
Also, it is not showing in the which-key menu. I don't know if is a known issue or related.

**Comment by NTBBloodbath** [comment]
> I can just add here the my issue is pertaining to non leader mappings. 
> 
> However, I can also confirm that user mappings show
> up in the leader menu if you add them to `doom-whichkey` module when I have added my own.

Hmm can you please share your custom keybinds aswell?

**Comment by NTBBloodbath** [comment]
> Sorry to bother but none of the options solved the issue, as I still have to do `<leader>dl` to load the bindings.
> 
> > For `<leader>.` you could add noremap in the options at the moment, so our default one will not override yours because of loading order.
> 
> I tried with options `{ silent = true, noremap = true }` but no success.

Hmm right that's odd. Can you please send the output of `:nmap <leader>.`?

> > For `<leader>gg` you'll also need to add this to our which-key configs module (`lua/doom/modules/config/doom-whichkey.lua`). If which-key is enabled and the key isn't mapped internally then which-key will gracefully fail because it can't find the registered mapping in its internal database. Hopefully we will be able to solve this in next Doom versions by implementing [nest.nvim](https://github.com/LionC/nest.nvim) to manage our keybinds.
> 
> I changed the git section adding the first line for `<leader>gg`, but the issue remains.
> ```
>     ["g"] = {
>       name = "+git",
>       ["g"] = { "Open Magit" },
>       ["o"] = { "Open LazyGit" },
>       ["l"] = { "Pull" },
>       ["p"] = { "Push" },
>       ...
>     }
> ```
> Also, it is not showing in the which-key menu. I don't know if is a known issue or related.

Have you tried running `:PackerCompile` manually? We have an automatic run of this command, however packer acts in some inconsistent _and weird_ ways sometimes.

**Comment by xzebra** [comment]
Tried `:PackerCompile` but it still happens.

This is the output of `:nmap <leader>.` before `<leader>dl`:
```
n  <Space>     * <Cmd>lua require("which-key").show(" ", {mode = "n", auto = true})<CR>             
n  <Space>.      <Cmd>Telescope file_browser<CR>
```
An this is after loading the config:
```
n  <Space>     * <Cmd>lua require("which-key").show(" ", {mode = "n", auto = true})<CR>             
n  <Space>.    * <Cmd>lua require('telescope.builtin').file_browser({ hidden=true, cwd = require'telescope.uti
ls'.buffer_dir() })<CR>
```

Don't worry if this is causing much trouble, as I saw you were planning on changing the custom mappings system. Maybe we can review it after the changes.

**Comment by molleweide** [comment]
> Hmm can you please share your custom keybinds aswell?

yes here are my configs. 

<details>

```lua
    mappings = {

    	{ 'n', '<leader>M', '<cmd>lua require("moll_snippets").load_snippets()<CR>', {}},

    	-- this is disabled in the core
	  	{"n", "<c-z>", "<c-z>", opts_s},
	  	{"v", "<c-z>", "<esc><c-z>", opts_s},
	  	{"n", "<leader>wz", "<esc><cmd>suspend<CR>", opts_s},

    	{'n', 'dh', ':set wrap linebreak<CR>'},
    	{'n', 'dl', ':set wrap! linebreak!<CR>'},

    	-- -- tabs
    	-- { 'n', ',tn', ':tabnew<cr>' },
    	-- { 'n', 'gl', 'gt' },
    	-- { 'n', 'gL', 'gT' },
    	-- { 'n', ',g0', ':tabr<cr>' },
    	-- { 'n', ',g$', ':tabl<cr>' },
    	-- { 'n', ',gh', ':tabm -<cr>' },
    	-- { 'n', ',gl', ':tabm +<cr>' },

    	-- -- read file
    	-- -- :r file               to after cursor
    	-- -- :$r                   to end of buffer
    	-- -- :0r                   to end of buffer
    	-- -- :{x}r                 to after line x
    	-- -- :/pattern/r file      to after pattern
    	-- { 'n', ',Rf', ':r<space>' },
    	-- { 'n', ',Re', ':$r<space>' },
    	-- { 'n', ',Rb', ':0r<space>' },
    	-- { 'n', ',Rl', ':r <Left><Left>' },
    	-- { 'n', ',Rp', '://r <Left><Left><Left>' },

    	-- -- line operations (testing)
    	-- -- " run current line through shell
    	-- { 'n', ',Zs', '!!$SHELL <CR>'},
    	-- -- " run current line in commandline
    	-- { 'n', ',Zl', 'yy:@" <CR>' },
			-- ??
    	-- { 'n', ',ZZ', ':w !sudo tee %'},

    	-- navigation + rm arrows
    	{'i', '<Down>', '<Nop>' },
    	{'i', '<Left>', '<Nop>' },
    	{'i', '<Right>', '<Nop>' },
    	{'i', '<Up>', '<Nop>' },
    	{'n', '<Down>', '<Nop>' },
    	{'n', '<Left>', '<Nop>' },
    	{'n', '<Right>', '<Nop>' },
    	{'n', '<Up>', '<Nop>' },
    	{'v', '<Down>', '<Nop>' },
    	{'v', '<Left>', '<Nop>' },
    	{'v', '<Right>', '<Nop>' },
    	{'v', '<Up>', '<Nop>' },

			-- -- ctrl move
			-- {'i','<c-l>','<space>'},
	  	-- {'c','<c-l>','<space>'},

			-- -- search regex
			-- {'n', '/', '/\\v'}, -- need to esc backsl
	  	-- {'v', '/', '/\\v'},

    	-- aliases
	  	{ 'n', 'gkN', '<cmd>e '.. notes_rndm ..'<CR>' },
	  	{ 'n', 'gkS', '<cmd>e '.. config_skhd ..'<CR>' },
	  	{ 'n', 'gka', '<cmd>e '.. config_alac ..'<CR>' },
	  	{ 'n', 'gke', '<cmd>e '.. config_setup ..'<CR>' },
	  	{ 'n', 'gkg', '<cmd>e '.. aliases_git ..'<CR>' },
	  	{ 'n', 'gkn', '<cmd>e '.. notes_todo ..'<CR>' },
	  	{ 'n', 'gks', '<cmd>e '.. config_sufr ..'<CR>' },
	  	{ 'n', 'gkt', '<cmd>e '.. config_tmux ..'<CR>' },
	  	{ 'n', 'gky', '<cmd>e '.. config_yabai ..'<CR>' },
	  	{ 'n', 'gkz', '<cmd>e '.. aliases_zsh ..'<CR>' },

    	-- -- make inclusive commands
	  	{ 'o', 'b', 'vb', opts.ns },
	  	{ 'o', 'B', 'vB', opts.ns },
	  	{ 'o', 'F', 'vF', opts.ns },
	  	{ 'o', 'T', 'vT', opts.ns },

    	--	-- sneak
	  	-- { '', 'f', '<Plug>Sneak_f' },
	  	-- { '', 'F', 'v<Plug>Sneak_F' },
	  	-- { '', 't', '<Plug>Sneak_t' },
	  	-- { '', 'T', 'v<Plug>Sneak_T' },
	  	-- -- { 'x', '<S-s>', '<Plug>Sneak_S' },
	  	-- { 'x', 'S', '<Plug>Sneak_S' },
	  	-- { 'o', 'F', 'v<Plug>Sneak_F', opts.ns },
	  	-- { 'o', 'T', 'v<Plug>Sneak_T', opts.ns },
	  	-- -- { '', '<c-k>', '<Plug>Sneak_;' },
	  	-- -- { '', '<c-j>', '<Plug>Sneak_,' },
	  	-- { 'o', 's', '<Plug>Sneak_s', opts_s.ns }, -- not working

    	-- surround
	  	{ 'x', 'z', '<Plug>VSurround' },
	  	{ 'n', 'yzz', '<Plug>Yssurround' }, -- double ss
	  	{ 'n', 'yz', '<Plug>Ysurround' }, -- single s
	  	{ 'n', 'dz', '<Plug>Dsurround' },
	  	{ 'n', 'cz', '<Plug>Csurround' },
  	},
```

</details>

**Comment by edwintorok** [comment]
I think there is an issue with loading order. Use `:Telescope keymaps` to investigate the keymap.
E.g. if I define a keybinding for `<leader>q` that will show up as `\q`. If I then type `<Space>dl` and run `:Telescope keymaps` again a 2nd mapping for `<Space>q` appears.

This appears to happen because vim.g.mapleader is set way too late in `lua/doom/extras/keybindings/leader.lua` and the keybindings are set earlier in `lua/doom/core/settings/init.lua` (`core` gets loaded before `extras`).

Neovim manual says https://neovim.io/doc/user/map.html#mapleader "Note that the value of "[mapleader](https://neovim.io/doc/user/map.html#mapleader)" is used at the moment the [mapping](https://neovim.io/doc/user/map.html#mapping) is
defined.  Changing "[mapleader](https://neovim.io/doc/user/map.html#mapleader)" after that has no effect for already defined
mappings."

I think mapleader should be defined earlier (in core) to avoid this issue.

**Comment by molleweide** [comment]
Personally, I have moved on to the `next` branch which means that the problems described here are to be obscolete quite soon. Are y'all fine with my closing?

**Comment by molleweide** [comment]
> 

Great points made!!

**Comment by connorgmeehan** [comment]
Yep closing it now because it's stale and resolved by https://github.com/NTBBloodbath/doom-nvim/tree/next
