### ISSUE TITLE
doom indentation

### ISSUE THREAD

**Issue by molleweide** [NTBBloodbath/doom-nvim#226]
I have not changed the indenation in `doom_config.lua` and when I run the built in
visual mode indent with `=` it reindents all the files in core. Is this a problem
if I want to submit a PR?

**Comment by NTBBloodbath** [comment]
Hi, this is not a problem, we have a CI to automatically format the source code according to our coding style. However it would be great to avoid having the format source code commits lol.

Let's leave this open and use modeline comments to hardcode the doom files indentation, you can do it it you want to. Neovim reads the comments that starts with `vim:` and reads the options from it, e.g.

```lua
-- vim: sw=2:ts=2=sts=2
```

This sets the file indentation to 2 (shiftwidth, tabstop and softtabstop) when opening it, afaik this comment can be at top or bottom of the file but let's add them at bottom :thinking:

**Comment by molleweide** [comment]
I stumbled upon another indentation issue.
I am learning how to write a makefile but when I put makefile into doom nvim file. Then running `Make` complains
about about separators and indenation.  

I created this user aucmd. Is there anything I should add to it because doom Make still complains

```lua
    autocmds = {
    	-- :autocmd FileType make set noexpandtab
    	makefile = {
    		{ 'FileType', 'Makefile', 'set noexpandtab'},
    	}
    },
```

**Comment by molleweide** [comment]
hmm, it worked when I manually redid all of the indents.

**Comment by molleweide** [comment]
another thing that I can mention also is that `bash` is not being indented correctly for me.
sometimes it works and sometimes does't. I am going to post an example.

**Comment by connorgmeehan** [comment]
Closed due to inactivity.  Made a new issue for general issues with indenter here https://github.com/NTBBloodbath/doom-nvim/issues/364
