### ISSUE TITLE
Scala support?

### ISSUE THREAD

**Issue by octavz** [NTBBloodbath/doom-nvim#228]
doom emacs has Scala LSP support out of the box using Metals.

Thanks

**Comment by NTBBloodbath** [comment]
Hi, sorry for the very late response!

I'll add it today and let you know once it's pushed so you can give it a try :)

**Comment by NTBBloodbath** [comment]
So it's all done by my side, please let me know if it works for you _and close the issue if it does_. lspconfig will look for one of the following files to trigger metals btw.

- build.sbt
- build.sc
- build.gradle
- pom.xml

Regards

**Comment by octavz** [comment]
Will do, thank you.

**Comment by octavz** [comment]
trying to install latest version, I get this in the editor:

```
Error detected while processing function <SNR>33_call_line_function:
line    6:
E5108: Error executing lua /home/octav/.config/nvim/lua/doom/core/functions/init.lua:466: attempt to index field 'ui' (a nil value)
Press ENTER or type command to continue

```

**Comment by NTBBloodbath** [comment]
Hi, this is weird to me. What's your Neovim version?

**Comment by octavz** [comment]
Hi,

```
nvim --version
NVIM v0.5.1
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az68-68

Features: +acl +iconv +tui
```

**Comment by NTBBloodbath** [comment]
Hmm alright, it seems that I've implemented a nightly feature without knowing it was nightly lol. Does this only happens to you when you try to edit the configurations from the keybinds or dashboard? If so I think I can make a small patch for this to also support Neovim 0.5.x in that function after work.

At the moment you will need to manually open and edit the configuration files.

**Comment by octavz** [comment]
Installed 0.6.0, ran PackerCompile and seems to work with Scala files. Thanks.

**Comment by octavz** [comment]
This integration offers better Scala experience. Would be nice to have it at some point in time. 
On a different note, would be possible to replicate doom-emacs shortcuts, doom-emacs is the only reason I heard about this project and changing manually all shortcuts defeats the purpose of using doom-nvim.
 Thanks.

**Comment by NTBBloodbath** [comment]
> On a different note, would be possible to replicate doom-emacs shortcuts, doom-emacs is the only reason I heard about this project and changing manually all shortcuts defeats the purpose of using doom-nvim.

Sure thing, can you please create another issue to reference this? In that way I'll not forget this request :)
