### ISSUE TITLE
auto pair functions 

### ISSUE THREAD

**Issue by Mremmalex** [NTBBloodbath/doom-nvim#24]
when using doom vim the auto pair function is not working as it should, when typing in a double quote is not pair, u will have to added the closing quote yourself,

**Comment by NTBBloodbath** [comment]
Hey, can you provide steps to reproduce it?

I've tried with lua, bash and typescript files (don't know if there's a problem with certain filetypes) and the configs from both branches and it was working fine for me.

**Comment by Mremmalex** [comment]
so while working on typescript , cpp and  python i have to complete the quotes myself, when i use the double quotes the closing quote is not added,

**Comment by GustavoPrietoP** [comment]
try uninstalling the Tree-sitter parser for that language, ex: `:TSUninstall <lang>` and see if it works.
It seems like its not doom-nvim problem but a pairs.nvim issue

**Comment by NTBBloodbath** [comment]
Hey @Mremmalex I just have pushed some changes to try fix it. Can you please give them a try? Run `:DoomUpdate` to update your doom nvim and then restart it to apply new changes (don't forget to update the plugins using `:PackerSync` if needed!).

As @GustavoPrietoP said, this pairs plugin was having some issues so I've changed it to other that looks more promising and consistent. Lemme know if the issue persist.

Regards

**Comment by Mremmalex** [comment]
i had to update doom vim and the changes have solved it
