### ISSUE TITLE
Setup bug report / feature request issue templates

### ISSUE THREAD

**Issue by connorgmeehan** [NTBBloodbath/doom-nvim#244]
We're receiving a lot of bug reports in a lot of different formats, sometimes missing relevant information.

That bug reporters should fill in their issue from a template to make it clearer for contributors to understand and solve their problems.  https://www.youtube.com/watch?v=UPsCXqxxJUA I found this tutorial to follow if I made an example Issue template here and I think the default Feature Request one is good.

<details>
  <summary>Bug Report Template</summary>
  
  ```
## What is the current behaviour / issue?



## How to reproduce this error



## What is the expected behaviour?



## Logs

<details>
  <summary>Check Health Output</summary>
  
  ** Run `:checkhealth` and paste output here **

</details>

<details>
  <summary>Doom Report Output</summary>
  
  ** Run `:DoomReport` and copy the contents of `~/.local/share/nvim/doom_report.md` **

</details>

## Additional context/screenshots

** Add screenshots of the issue or extra log files if relevant **


  ```

</details>

**Comment by molleweide** [comment]
i am going to update my bug report commands with this also in vim

**Comment by connorgmeehan** [comment]
Oh yeah good idea, do you think you can automatically include the `:checkhealth` output in the neovim bug report command?  Then we could reference that command from the github template i.e.

> Note: Use `:DoomReport` command to get a copy of this template pre-filled with `:checkhealth` output.

**Comment by molleweide** [comment]
Found this https://vi.stackexchange.com/questions/8378/dump-the-output-of-internal-vim-command-into-buffer#8379
