### ISSUE TITLE
Migrate from kabouzeid/nvim-lspinstall to williamboman/nvim-lsp-installer

### ISSUE THREAD

**Issue by bavalpey** [NTBBloodbath/doom-nvim#245]
Not sure if you've seen this, but kabouzeid/nvim-lspinstall has been archived and will not be in active development anymore.  The page recommends switching to williamboman/nvim-lsp-installer.

**Comment by connorgmeehan** [comment]
Didn't know there was an issue for this. I've added nvim-lap-installer in develop branch can this be closed now?
