### ISSUE TITLE
"BufNewFile" autocommand is not respected upon launching nvim

### ISSUE THREAD

**Issue by bavalpey** [NTBBloodbath/doom-nvim#256]
I have an autocmd that I use for file templates placed in the `autocmds` section of `doom_config.lua`.  However, this autocommand does not work when launching nvim from the command line.

For instance, if I have the following template in `~/.config/nvim/templates/template.py`
```py
#!/usr/bin/env python

# Author: Benjamin Valpey

```
and the following in my `doom_config.lua` file
```lua
autocmds = {
    filetemplates = 
        { 'BufNewFile', '*.py', '0r ~/.config/nvim/templates/python.tmpl' },
    },
},
```

then, when opening a file using `nvim test.py`, this skeleton should be inserted.  However, it is not.

I know that this is the correct event for the autocommand.  I have tested with a simple init.vim
```vim
augroup skeleton
    autocmd!
    "Add skeleton for python files"
    autocmd bufnewfile *.py 0r ~/.config/nvim/templates/python.tmpl
augroup END
```
With this file, launching nvim with `nvim -u init.vim test.py` read in the template as expected.

Could this have something to do with the lazy loading? Any suggestions on how to fix?

**Comment by connorgmeehan** [comment]
Closed due to inactivity.  Just to note this seems to be because the BufNewFile autocommand doesn't trigger on startup so this behaviour is expected.  You could change the autocommand to use BufRead and then check if the file is empty and then add the pythont emplate.
