### ISSUE TITLE
Feature request: file manager (like dired)

### ISSUE THREAD

**Issue by xzebra** [NTBBloodbath/doom-nvim#257]
One of the most important features I'm missing from doom-emacs is the **dired integration**. In doom-emacs you can simply open _dired_ through a key-binding or through the equivalent of _telescope_ in emacs and create folders and files.

I've found a workaround for creating files from _telescope_, with `C-e`, but _dired_ gives you a faster way to manage files and directories. There are some plugins that have similar behavior as _dired_, such as [lir.nvim](https://github.com/tamago324/lir.nvim), but I think they should be integrated in doom-nvim.

**Comment by molleweide** [comment]
is there an nvim plugin for dired?

**Comment by molleweide** [comment]
i can recommend `ranger` in case you didn't know about it.

**Comment by molleweide** [comment]
if you have ranger installed then you can enable the ranger module.

**Comment by xzebra** [comment]
> is there an nvim plugin for dired?

There are some with similar features, like the one I linked (`lir.nvim`).

**Comment by NTBBloodbath** [comment]
Hi, if I recall correctly dired is a file explorer, right? Never used it, I have always been a treemacs user.

If so then have you tried nvim-tree? We use that plugin as our file explorer and we also have an integration with netrw (the built-in Neovim file explorer). Let me know if nvim-tree is way different from the one that you linked here so we can decide what to do :)

Regards

**Comment by xzebra** [comment]
I've never been into tree explorers, so I will be trying the ranger module @molleweide recommended. It seems like it is not that different from dired. Anyways, thanks for the help.
