### ISSUE TITLE
I think nvim-lspconfig broke doom stable

### ISSUE THREAD

**Issue by emmanueltouzery** [NTBBloodbath/doom-nvim#259]
hmm I ran PackerSync on my 3.1.2 version, and I got an error at startup: 

> packer.nvim: Error running config for nvim-lspinstall: ...pack/packer/opt/nvim-lspconfig/lua/lspconfig/configs.lua:10: attempt to index local 'config_def' (a nil value)

This might be <https://github.com/neovim/nvim-lspconfig/issues/1075#issuecomment-979217514>

> It's been requested for awhile to directly expose configurations without activating them. I will make this change in [1479](https://github.com/neovim/nvim-lspconfig/pull/1479). I'm generally looking for testers, as I also cleaned up several configurations. If your configuration breaks as a result of this change (before or after I merge it), let me know. I will update this message once it is merged.

I fixed the issue for myself by pinning the version of nvim-lspconfig and running packer sync again:

```diff
  use({
    "neovim/nvim-lspconfig",
    config = require("doom.modules.config.doom-lspconfig"),
    disable = disabled_lsp,
    event = "ColorScheme",
+    commit = '2e6c94069e92cb4a43416b3ac0267e941b3fd47e'
  })
```

in lua/doom/modules/init.lua line 313

**Comment by 3JlOy-PYCCKUi** [comment]
This solution worked for me, too

**Comment by RudraAsthana** [comment]
SO thats why doom is giving me existential crisis

**Comment by NTBBloodbath** [comment]
Hmm alright, let's make a patch with this solution (thank you so much per doing this :) ) at the moment. Hope I can have some time today to finish Doom 3.2 changelog so we can get rid of all possible errors due to breaking changes in the plugins

**Comment by emmanueltouzery** [comment]
sure, i'll make a PR!

**Comment by emmanueltouzery** [comment]
PR submitted!

**Comment by NTBBloodbath** [comment]
Thanks, already merged it so imma close this issue. Make sure to update Doom :)
