### ISSUE TITLE
Vertical line across the screen

### ISSUE THREAD

**Issue by 3JlOy-PYCCKUi** [NTBBloodbath/doom-nvim#262]
Unclear and annoying vertical line that appears only in files with lots of text, in empty files this line is absent.
![doom-nvim-vertical-line](https://user-images.githubusercontent.com/46464602/144319622-1f15dbb3-7612-4707-923c-f281a44e221c.png)

**Comment by NTBBloodbath** [comment]
Hi, you should be able to disable this behavior by tweaking the `max_columns` option in your doom configurations file and setting it to `0`.
