### ISSUE TITLE
[BUG] neorg: "Could not find remote branch unstable to clone"

### ISSUE THREAD

**Issue by markolenik** [NTBBloodbath/doom-nvim#265]
### Current Behavior:
neorg merged their unstable branch into main today, see this [commit](https://github.com/nvim-neorg/neorg/commit/c99b99ae370428234f84ecf77ce5950137a9f0a7). This error happens with fresh install of main branch doom-nvim.

```
 ✗ Failed to install nvim-neorg/neorg/unstable
  Errors:
    Cloning into '/Users/mark/.local/share/nvim/site/pack/packer/opt/neorg'...
    warning: Could not find remote branch unstable to clone.
    fatal: Remote branch unstable not found in upstream origin
```

### Steps To Reproduce:
Follow the install instructions on the doom-nvim readme.

### Anything else:
I've omitted the logs etc since this issue seems to be trivial otherwise.

**Comment by NTBBloodbath** [comment]
Hi, thank you so much for reporting this!

I'll send the patch to fix this pretty soon :)

**Comment by NTBBloodbath** [comment]
Hey, should be fixed now. Feel free to reopen this issue if the problem persists!

**Comment by markolenik** [comment]
Thanks for the quick fix!
