### ISSUE TITLE
[QUESTION] How to change keymappings with Luascript, for example set delete to j

### ISSUE THREAD

**Issue by romanakmath** [NTBBloodbath/doom-nvim#269]
I have a question regarding the keybindings, how do I remap keybindings with Lua in doom-nvim? As far as I've understood correctly you can change keybindings either by using vimscript or the newer variant by using Lua.

For example I would like to set delete operator which is called by `"d" `to `"j"`. I would also like to scroll down by `"d"` instead of `"ctrl-d"`. What do I have to do to make these toy examples work?

**Comment by connorgmeehan** [comment]
Closed due to inactivity.
