### ISSUE TITLE
[QUESTION] How to change a dark theme to a light one 

### ISSUE THREAD

**Issue by Rareform** [NTBBloodbath/doom-nvim#270]
How can I change a theme from a dark to bright one?
For example similar to this one I had in doom (doesn't have to be the same coloring, the main importance is that it would have a light background:
![Screenshot from 2021-12-18 20-52-43](https://user-images.githubusercontent.com/18005462/146654039-0a226208-9321-4c97-87cb-5e64d53fe63e.png)
Where can I make all the settings considering the visual style of my theme?

**Comment by connorgmeehan** [comment]
Inside of the `doom_config.lua` file there's an option to change colourscheme and also to change colourscheme style.

The option you're looking for is
```lua
    -- Background color
    -- @default = dark
    colorscheme_bg = "dark",
```
And you should be able to change this to `light`.
