### ISSUE TITLE
require `lua/mydir` in core breaks config?!

### ISSUE THREAD

**Issue by molleweide** [NTBBloodbath/doom-nvim#285]
I am trying to require my own custom configs into core but this breaks the config.
Isn't one suppose to be able to require things that exist under `lua/`??
Alternatively, I am being stupid..

I keep all of my own custom stuff under `lua/molleweide/` for ease sake, especially
with the massive restructuring going on in core. I don't want to mess with the core.

``` lua
  -- Neogit
  local disabled_neogit = is_plugin_disabled("neogit")
  use({
    "TimUntersberger/neogit",
    commit = pin_commit("ab772d21b108127ad6c703f7457c279f5817f379"),
    config = require("molleweide.plugins.config_neogit"),
    disable = disabled_neogit,
    cmd = "Neogit",
    module = "neogit",
  })
```

**Comment by NTBBloodbath** [comment]
Hey, can you please provide more information about this behavior? In fact this should work so it's actually being a bit weird to me lol.

Cheers

**Comment by molleweide** [comment]
Good, at first I thought that this was an embarassing question that would 
showcase my incompetence. So this is good news :D

**Comment by molleweide** [comment]
closing because these errors pertained to v2
