### ISSUE TITLE
lt takes a long time for telescope to load results on `main`

### ISSUE THREAD

**Issue by molleweide** [NTBBloodbath/doom-nvim#287]
I am using main, nvim 0.6 on macos M1 with a fully working config according to checkhealth.

It takes a couple of second for it to load THE FIRST TIME, from what I can see regardless of which telescope command used.

My apologies for not adding more details. I just haven't gotten around to setting up a nice bug creation workflow yet.

I'll also add here that it takes forever for `packer sync` command to load, and :checkhealth doesn't seem to finish for me now.
I will file bug for there later, or rather do some more investigating and come back.

**Comment by molleweide** [comment]
hmm I looked into activity monitor on my mac and it showed about ~10 nvim processes running that I couldn't find where they were running. I force quit all of them and now nvim seems more responsive so I'll close
this for now.

**Comment by connorgmeehan** [comment]
Hmmm do you have any information on what the processes might be?  I've had issues where the telescope launches a bunch of child processes.  In huge projects they just keep indexing more and more files and growing in size and it's really slowed down my computer before. I'm not sure if it's something that doom-nvim can solve but I'll look into it.  

Also regarding Telescope loading slowly the first time, that's the intended behaviour (although it definitely shouldn't take a few seconds).  We only load lazyload the plugin when the `:Telescope` command is first called.  Is it still taking this long or did force quiting resolve the issue?

**Comment by molleweide** [comment]
I haven't been thinking about it so much no. Before it must have been slow due to all the nvim processes and my computer running hot AF but now it is cold and everything seems to be running faster. it is just hard to evaluate. But thanks a lot for appreciating my issue and adding the link to telescope!
