### ISSUE TITLE
[BUG] Deprecation warning for "vim.lsp.diagnostic.get_count" since upgrading to 3.2.0

### ISSUE THREAD

**Issue by baurmatt** [NTBBloodbath/doom-nvim#289]
### Current Behavior:
`vim.lsp.diagnostic.get_count is deprecated. See :h deprecated` shown after opening nvim

### Expected Behavior:
No deprecation warning is shown

### Steps To Reproduce:
```
sudo add-apt-repository ppa:neovim-ppa/unstable
sudo apt-get update
sudo apt-get install git ripgrep neovim g++
git clone --depth 1 https://github.com/NTBBloodbath/doom-nvim.git ${XDG_CONFIG_HOME:-$HOME/.config}/nvim
nvim
```

### Logs

<details>
<summary>Check Health Output</summary>

lspconfig: require("lspconfig.health").check()
========================================================================
  - WARNING: Can't find any config.

nvim: health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $SSH_TTY='/dev/pts/0'

nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - WARNING: `node` executable not found (only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - lua            ✓ ✓ ✓ ✓ ✓
  - c              ✓ ✓ ✓ ✓ ✓
  - norg           x . ✓ . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

## The following errors have been detected:
  - ERROR: norg(highlights): /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 1091

provider: health#provider#check
========================================================================
## Clipboard (optional)
  - WARNING: No clipboard tool found. Clipboard registers (`"+` and `"*`) will not work.
    - ADVICE:
      - :help |clipboard|

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          python2 not found in search path or not executable.
          python2.7 not found in search path or not executable.
          python2.6 not found in search path or not executable.
          python not found in search path or not executable.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 3:
          /usr/bin/python3 does not have the "neovim" module. :help |provider-python|
          python3.10 not found in search path or not executable.
          python3.9 not found in search path or not executable.
          /usr/bin/python3.8 does not have the "neovim" module. :help |provider-python|
          python3.7 not found in search path or not executable.
          python3.6 not found in search path or not executable.
          python not found in search path or not executable.
  - INFO: Executable: Not found

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Node.js provider (optional)
  - WARNING: `node` and `npm` (or `yarn`) must be in $PATH.
    - ADVICE:
      - Install Node.js and verify that `node` and `npm` (or `yarn`) commands work.

## Perl provider (optional)
  - ERROR: perl provider error:
    - ADVICE:
      - "Neovim::Ext" cpan module is not installed

vim.lsp: require("vim.lsp.health").check()
========================================================================
  - INFO: LSP log level : WARN
  - INFO: Log path: /home/ubuntu/.cache/nvim/lsp.log
  - INFO: Log size: 0 KB

vim.treesitter: require("vim.treesitter.health").check()
========================================================================
  - INFO: Runtime ABI version : 13
  - OK: Loaded parser for lua: ABI version 13
  - OK: Loaded parser for norg: ABI version 13
  - OK: Loaded parser for c: ABI version 13

which_key: health#which_key#check
========================================================================
## WhichKey: checking conflicting keymaps
  - WARNING: conflicting keymap exists for mode **"n"**, lhs: **"gc"**
  - INFO: rhs: `<Plug>kommentary_motion_default`

</details>

<details>
<summary>Doom Report Output</summary>

# Doom Nvim crash report

> Report date: 2022-01-19 10:44:18

## System and Doom Nvim information

- **OS**: Ubuntu 20.04.3 LTS
- **Neovim version**: 0.7.0 (dev)
- **Doom Nvim information**:
  - **version**: 3.2.0
  - **`doom_root` variable**: `/home/ubuntu/.config/nvim`
  - **`doom_configs_root` variable**: `/home/ubuntu/.config/nvim`

### Begin error log dump

```

```

### End log dump

</details>

### Anything else:
Tested on Ubuntu 20.04, but I could see the same error on my MacOS installation.

**Comment by NTBBloodbath** [comment]
Hi, I think I know why is this warning being raised and there's a PR to fix this in develop branch (will also cherry-pick it to main asap).

Basically Neovim had some small but huge breaking changes in their LSP API so they raise a ton of warnings in some plugins we use. Note that these deprecation warnings will be only shown in Neovim 0.7 (current development version).

I'll let you know when PR is merged and cherry-picked to main.

Cheers!

**Comment by baurmatt** [comment]
Thanks! :) FYI: I see this error on my Mac with Neovim v0.6.1.

**Comment by NTBBloodbath** [comment]
Hey, should be fixed now. Feel free to `:DoomUpdate`, `:PackerSync` (not sure if a restart would be required) and re-open this issue if you're still facing this error after completely updating Doom.

**Comment by baurmatt** [comment]
@NTBBloodbath Looks good, thank you! :)

**Comment by NTBBloodbath** [comment]
Hmm right, this one comes directly from our side. Is it the only one that is being raised? Send `:messages` output please :)

**Comment by baurmatt** [comment]
Seems like the same error gets raised twice:

```
vim.lsp.diagnostic.show_line_diagnostics is deprecated. See :h deprecated
vim.lsp.diagnostic.show_line_diagnostics is deprecated. See :h deprecated
Press ENTER or type command to continue
```

**Comment by NTBBloodbath** [comment]
Great, thank you. I'll be pushing a fix in the next hours and will let you know once it's done as before.

**Comment by AshleighWilson** [comment]
Hi, has the fix for this been pushed? Can't seem to see the commit and still getting the issue.
