### ISSUE TITLE
[BUG] dashboard opened also when piping contents in neovim

### ISSUE THREAD

**Issue by emmanueltouzery** [NTBBloodbath/doom-nvim#294]
### Current Behavior:
running
`echo test | nvim -`

the dashboard is opened, i must close it to see the buffer with the text "test".

### Expected Behavior:
in this case I'd expect to see only the buffer containing 'test'.

### Anything else:
I fixed this issue for me by commenting this code in doom-nvim's init.lua:

```lua
  -- If the current buffer name is empty then trigger Dashboard.
  -- NOTE: this is done to avoid some weird issues with Dashboard and
  --       number / signcolumn when Dashboard gets triggered automatically
  -- if
  --   (vim.api.nvim_buf_get_name(0):len() == 0)
  --   and (packer_plugins and packer_plugins["dashboard-nvim"])
  -- then
  --   vim.cmd("Dashboard")
  -- end
```
(the code commenting is mine)

This is line 35 in the 3.2.0 stable release of doom-nvim. I guess we'd need an extra if in there to say "if the buffer name is empty AND we're not getting data piped in? or something like that.

**Comment by connorgmeehan** [comment]
Hey @emmanueltouzery, thanks for reporting this.  This is fixed on the `develop` branch and we'll be pushing to main soon!
