### ISSUE TITLE
Snippets expansion

### ISSUE THREAD

**Issue by leonistor** [NTBBloodbath/doom-nvim#30]
Hi!

Great project, it "just work" as promised and it's fast. Thank you!

I want to add snippets using 'rafamadriz/friendly-snippets', so I've modified 'doomrc':

```lua
-- ...
disabled_plugins = {  'minimap', 'restclient'},
-- ...
disabled_modules = {},

custom_plugins = {
                {
                    ['repo'] = 'hrsh7th/vim-vsnip',
                    ['enabled'] = true,
                },
                {
                    ['repo'] = 'hrsh7th/vim-vsnip-integ',
                    ['enabled'] = true,
                },
                {
                    ['repo'] = 'rafamadriz/friendly-snippets',
                    ['enabled'] = true,
                },
},
```

and 'lua/plugins/configs/nvim-compe.lua':

```lua
-- ...
source = {
                path = true,
                buffer = true,
                calc = true,
                vsnip = true,
                nvim_lsp = true,
                nvim_lua = true,
                spell = false,
                tags = true,
                snippets_nvim = false,
                treesitter = true,
        },
```

The snippets ar present in the completion list, navigating the list with `Tab` and `S-Tab` displays the snippet skeleton, but I cannot trigger the completion: pressing `Enter` just closes the completion menu.

https://user-images.githubusercontent.com/310468/124468414-bc168e00-dda1-11eb-9583-3a6b70ea34d6.mp4

Any suggestions? Thank you!

**Comment by NTBBloodbath** [comment]
Hey, thank you for your comments. I really appreciate them!

Can you please run `:checkhealth compe` and attach a screenshot of the results?

Regards

**Comment by leonistor** [comment]
![nvim](https://user-images.githubusercontent.com/310468/124472528-e880d900-dda6-11eb-8f32-af02c11ea16c.png)

**Comment by NTBBloodbath** [comment]
Hey, sorry for the delay. I think it should be fixed now, feel free to reopen this issue if you're still facing it.

To check the keybinds you can use `:checkhealth compe` again, but anyway I'll list them there too.

```
<C-Space> => complete
<CR>      => confirm
<C-e>     => close
```

Remember to update with `:DoomUpdate`, happy hacking! :)

**Comment by leonistor** [comment]
Hi! `:DoomUpdate` successful after `git rm logs/doom.log`.
`:checkhealth compe` reports ok:

![nvim-resolved](https://user-images.githubusercontent.com/310468/124547207-77880280-de34-11eb-9627-2db9e9a1703c.png)

However, pressing `Ctrl-Space` after selecting snippet from list with `Tab` throws an error and the completion fails:

![nvim-err](https://user-images.githubusercontent.com/310468/124547315-9d150c00-de34-11eb-823a-55d83fac7364.png)

Maybe it's related to choosing `Ctrl-Space, as [here](https://github.com/davidhalter/jedi-vim/issues/159)?

I'm using neovim in kitty + sway + void linux.

Thank you!

**Comment by NTBBloodbath** [comment]
Hey, I just did other change related to this behavior. I've tried it out before pushing and was working for me, please update doom :slightly_smiling_face:

Let me know if the issue persists again, I'll leave this issue open until is completely fixed.

Regards

**Comment by leonistor** [comment]
It works :clap: :+1: 

Thank you, keep up the good work!

**Comment by NTBBloodbath** [comment]
Thank you for reporting this issue!
