### ISSUE TITLE
[QUESTION] Why custom colors on by default & hardcoded status-line color?

### ISSUE THREAD

**Issue by Icy-Thought** [NTBBloodbath/doom-nvim#304]
- [x] I have searched open and closed issues for this question

Forgot to create an issue regarding this issue, but why is it that custom plugin colors, which-key and dashboard, are enabled by default? Commenting both settings would return an error. 

The reason to why I am asking this is that many colorschemes have already defined colors for both and other plugins as-well. The custom colors just makes it unnecessary to edit for the sake of achieving the same result one would by using the default settings for the installed colorschemes. (assuming they've already been defined)

Also, the status-line should not have a hardcoded color but automatically select colorscheme color or fallback to the current color + have a customization option.

**Comment by connorgmeehan** [comment]
Closed as this has been fixed in new `statusline` module. [relevant code](https://github.com/NTBBloodbath/doom-nvim/blob/6a19199c8d5d501733d9a373cb31e88e865b8961/lua/doom/modules/features/statusline/init.lua#L71)
