### ISSUE TITLE
[QUESTION] Run doom-nvim headless to do initialization?

### ISSUE THREAD

**Issue by blakebarnett** [NTBBloodbath/doom-nvim#305]
I'm trying to setup doom-nvim in a Docker container. I'd like to have it do all the compilation and PackerSync during build time so that the image is totally ready to use. I've been fiddling with running `nvim --headless -es` but the modules don't seem to load in this mode. 

Is this possible?

**Comment by connorgmeehan** [comment]
Stale, closed due to inactivity.  If you need help setting this up on `v4.x` post a comment and I'll re-open :)
