### ISSUE TITLE
Fresh installation Raspberry 

### ISSUE THREAD

**Issue by HT-Moh** [NTBBloodbath/doom-nvim#306]
![image](https://user-images.githubusercontent.com/34759569/154939670-74d5199c-d2cc-4e2b-96f1-ee8f0de6bace.png)

PRETTY_NAME="Ubuntu 21.10"
NAME="Ubuntu"
VERSION_ID="21.10"
VERSION="21.10 (Impish Indri)"
VERSION_CODENAME=impish
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=impish

aarch64

**Comment by connorgmeehan** [comment]
Stale, closed due to inactivity.  If this issue is still happening on `v4.x` post a comment and I'll re-open :)
