### ISSUE TITLE
nvim-treesitter install.lua:348 issue 

### ISSUE THREAD

**Issue by HT-Moh** [NTBBloodbath/doom-nvim#309]
`nvim project` 

![image](https://user-images.githubusercontent.com/34759569/155966895-2bfb3d60-1b71-44f2-97c7-824d7f1ebf7d.png)

`Parker update` result

![image](https://user-images.githubusercontent.com/34759569/155966528-839c6348-b8de-49fa-b344-413e1499aa9a.png)

`NvimTreeRefresh`  result

![image](https://user-images.githubusercontent.com/34759569/155966583-78f872af-ec40-4a22-8b63-71f9fb8ef222.png)

`checkhealth` 

![image](https://user-images.githubusercontent.com/34759569/155967948-c83c0d3f-c256-425a-ae96-83066aebbeac.png)

![image](https://user-images.githubusercontent.com/34759569/155967992-b314fd23-7ab4-4b1b-b06a-80c3a7ca1448.png)

`NVIM v0.7.0-dev+1156-ge38354334` build from source 
`Ubuntu 20.04.4 LTS` 

I tried both bleeding-edge

**Comment by connorgmeehan** [comment]
A bit late but the current `main` branch isn't very well maintained and you'll get much better results using the https://github.com/NTBBloodbath/doom-nvim/tree/next rewrite that will be released soon.
