### ISSUE TITLE
Macros broken?

### ISSUE THREAD

**Issue by will** [NTBBloodbath/doom-nvim#31]
Is one of these plugins disabling macros? If I launch nvim without any init `nvim -u NONE` I can use `q` to record macros like normal. But with doom-nvim pressing `q` doesn't seem to do anything. I'm not sure how to track it down. I did some searches through the project for `macro` and looked through some spots, but nothing is jumping out to me as the likely culprit.

**Comment by NTBBloodbath** [comment]
Hey, the macros mapping is disabled by doom. [Here]https://github.com/NTBBloodbath/doom-nvim/blob/main/lua/doom/keybindings/init.lua#L157-L158) you can find the lines that does it so you can remove them.

Maybe we should making it an option for enabling/disabling them in the next release :thinking:

**Comment by will** [comment]
Thanks, I'll close this for now, but I would support that being an official option.
