### ISSUE TITLE
[BUG] Multiple Lua errors

### ISSUE THREAD

**Issue by z0mb1e-kgd** [NTBBloodbath/doom-nvim#317]
### Current Behavior:

Multiple Lua errors on various actions, i.e.:

Pressing 'F3' to open file tree window gives the following error:

Error executing vim.schedule lua callback: vim/_editor.lua:0: attempt to call upvalue '' (a nil value)
stack traceback:
        vim/_editor.lua: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
Press ENTER or type command to continue

After pressing <Enter> the file tree opens up, however.

### Logs

<details>
<summary>Check Health Output</summary>

nvim: health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $VTE_VERSION='6800'
  - INFO: $COLORTERM='truecolor'

nvim-lsp-installer: require("nvim-lsp-installer.health").check()
========================================================================
## nvim-lsp-installer report
  - OK: neovim version >= 0.6.0
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - WARNING: **julia**: not available
  - OK: **bash**: `GNU bash, версия 5.1.16(1)-release (x86_64-pc-linux-gnu)`
  - OK: **tar**: `tar (GNU tar) 1.34`
  - OK: **gzip**: `gzip 1.12`
  - OK: **curl**: `curl 7.82.0 (x86_64-pc-linux-gnu) libcurl/7.82.0 OpenSSL/1.1.1n zlib/1.2.12 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.47.0`
  - OK: **wget**: `GNU Wget 1.21.3 для linux-gnu.`
  - OK: **python3**: `Python 3.10.4`
  - OK: **node**: `v18.0.0`
  - OK: **Ruby**: `ruby 3.0.4p208 (2022-04-12 revision 3fa771dded) [x86_64-linux]`
  - OK: **Go**: `go version go1.18.1 linux/amd64`
  - OK: **sh**: `Ok`
  - OK: **RubyGem**: `3.3.8`
  - OK: **java**: `Ok`
  - OK: **javac**: `javac 18.0.1`
  - OK: **npm**: `8.7.0`
  - OK: **pip3**: `pip 21.0 from /usr/lib/python3.10/site-packages/pip (python 3.10)`

nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.6 (ccd6bf554d922596ce905730d98a77af368bba5c) (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v18.0.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 11.2.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - java           ✓ ✓ . ✓ ✓ 
  - css            ✓ . ✓ ✓ ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - norg           ✓ . ✓ . ✓ 
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - go             ✓ ✓ ✓ ✓ ✓ 
  - html           ✓ ✓ ✓ ✓ ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

provider: health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /usr/bin/python3
  - INFO: Other python executable: /bin/python3
  - INFO: Python version: 3.10.4
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - INFO: Ruby: ruby 3.0.4p208 (2022-04-12 revision 3fa771dded) [x86_64-linux]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.
      - You may disable this provider (and warning) by adding `let g:loaded_ruby_provider = 0` to your init.vim

## Node.js provider (optional)
  - INFO: Node.js: v18.0.0
  - INFO: Nvim node.js host: /home/max/.nvm/versions/node/v18.0.0/lib/node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn package is installed: 4.10.1

## Perl provider (optional)
  - WARNING: "Neovim::Ext" cpan module is not installed
    - ADVICE:
      - See :help |provider-perl| for more information.
      - You may disable this provider (and warning) by adding `let g:loaded_perl_provider = 0` to your init.vim

vim.lsp: require("vim.lsp.health").check()
========================================================================
  - INFO: LSP log level : WARN
  - INFO: Log path: /home/max/.cache/nvim/lsp.log
  - INFO: Log size: 0 KB

vim.treesitter: require("vim.treesitter.health").check()
========================================================================
  - INFO: Runtime ABI version : 14
  - OK: Loaded parser for css: ABI version 13
  - OK: Loaded parser for go: ABI version 13
  - OK: Loaded parser for html: ABI version 13
  - OK: Loaded parser for java: ABI version 13
  - OK: Loaded parser for javascript: ABI version 13
  - OK: Loaded parser for lua: ABI version 13
  - OK: Loaded parser for norg: ABI version 13

which_key: health#which_key#check
========================================================================
## WhichKey: checking conflicting keymaps
  - WARNING: conflicting keymap exists for mode **"n"**, lhs: **"gc"**
  - INFO: rhs: `<Plug>kommentary_motion_default`

</details>

<details>
<summary>Doom Report Output</summary>

# Doom Nvim crash report

> Report date: 2022-04-22 14:20:06

## System and Doom Nvim information

- **OS**: Arch Linux
- **Neovim version**: 0.7.0
- **Doom Nvim information**:
  - **version**: 3.3.0
  - **`doom_root` variable**: `~/.config/nvim`
  - **`doom_configs_root` variable**: `~/.config/nvim`

### Begin error log dump

```
[ERROR Пт 22 апр 2022 12:43:17] ....config/nvim/lua/doom/modules/built-in/reloader/init.lua:142: Failed to reload 'doom.modules.config.doom-autopairs' module
[ERROR Пт 22 апр 2022 12:43:17] ....config/nvim/lua/doom/modules/built-in/reloader/init.lua:142: Failed to reload 'doom.modules.config.doom-blankline' module
[ERROR Пт 22 апр 2022 12:43:17] ....config/nvim/lua/doom/modules/built-in/reloader/init.lua:142: Failed to reload 'doom.modules.config.doom-cmp' module
[ERROR Пт 22 апр 2022 12:43:17] ....config/nvim/lua/doom/modules/built-in/reloader/init.lua:142: Failed to reload 'doom.modules.config.doom-colorizer' module
[ERROR Пт 22 апр 2022 12:43:17] ....config/nvim/lua/doom/modules/built-in/reloader/init.lua:142: Failed to reload 'doom.modules.config.doom-format' module
[ERROR Пт 22 апр 2022 12:43:17] ....config/nvim/lua/doom/modules/built-in/reloader/init.lua:142: Failed to reload 'doom.modules.config.doom-lint' module
[ERROR Пт 22 апр 2022 12:43:17] ....config/nvim/lua/doom/modules/built-in/reloader/init.lua:142: Failed to reload 'doom.modules.config.doom-lsp-signature' module
[ERROR Пт 22 апр 2022 12:43:17] ....config/nvim/lua/doom/modules/built-in/reloader/init.lua:142: Failed to reload 'doom.modules.config.doom-luasnip' module
[ERROR Пт 22 апр 2022 12:43:17] ....config/nvim/lua/doom/modules/built-in/reloader/init.lua:142: Failed to reload 'doom.modules.config.doom-todo' module
[ERROR Пт 22 апр 2022 12:43:17] ....config/nvim/lua/doom/modules/built-in/reloader/init.lua:142: Failed to reload 'doom.modules.config.doom-toggleterm' module
[ERROR Пт 22 апр 2022 12:43:17] ....config/nvim/lua/doom/modules/built-in/reloader/init.lua:142: Failed to reload 'doom.modules.config.doom-tree' module
[ERROR Пт 22 апр 2022 12:43:17] ....config/nvim/lua/doom/modules/built-in/reloader/init.lua:142: Failed to reload 'doom.modules.config.doom-trouble' module
[ERROR Пт 22 апр 2022 12:43:17] ....config/nvim/lua/doom/modules/built-in/reloader/init.lua:142: Failed to reload 'doom.modules.config.doom-zen' module
[ERROR Пт 22 апр 2022 12:43:17] ....config/nvim/lua/doom/modules/built-in/compiler/init.lua:7: Doom compiler needs toggleterm plugin, please uncomment the 'terminal' entry in your doom_modules.lua
[ERROR Пт 22 апр 2022 12:43:17] ...x/.config/nvim/lua/doom/modules/built-in/runner/init.lua:7: Doom runner needs toggleterm plugin, please uncomment the 'terminal' entry in your doom_modules.lua
[ERROR Пт 22 апр 2022 13:13:29] ....config/nvim/lua/doom/modules/built-in/reloader/init.lua:142: Failed to reload 'doom.modules.config.doom-autopairs' module
[ERROR Пт 22 апр 2022 13:13:29] ....config/nvim/lua/doom/modules/built-in/reloader/init.lua:142: Failed to reload 'doom.modules.config.doom-blankline' module
[ERROR Пт 22 апр 2022 13:13:29] ....config/nvim/lua/doom/modules/built-in/reloader/init.lua:142: Failed to reload 'doom.modules.config.doom-cmp' module
[ERROR Пт 22 апр 2022 13:13:29] ....config/nvim/lua/doom/modules/built-in/reloader/init.lua:142: Failed to reload 'doom.modules.config.doom-colorizer' module
[ERROR Пт 22 апр 2022 13:13:29] ....config/nvim/lua/doom/modules/built-in/reloader/init.lua:142: Failed to reload 'doom.modules.config.doom-format' module
[ERROR Пт 22 апр 2022 13:13:29] ....config/nvim/lua/doom/modules/built-in/reloader/init.lua:142: Failed to reload 'doom.modules.config.doom-lint' module
[ERROR Пт 22 апр 2022 13:13:29] ....config/nvim/lua/doom/modules/built-in/reloader/init.lua:142: Failed to reload 'doom.modules.config.doom-lsp-signature' module
[ERROR Пт 22 апр 2022 13:13:29] ....config/nvim/lua/doom/modules/built-in/reloader/init.lua:142: Failed to reload 'doom.modules.config.doom-luasnip' module
[ERROR Пт 22 апр 2022 13:13:29] ....config/nvim/lua/doom/modules/built-in/reloader/init.lua:142: Failed to reload 'doom.modules.config.doom-todo' module
[ERROR Пт 22 апр 2022 13:13:29] ....config/nvim/lua/doom/modules/built-in/reloader/init.lua:142: Failed to reload 'doom.modules.config.doom-toggleterm' module
[ERROR Пт 22 апр 2022 13:13:29] ....config/nvim/lua/doom/modules/built-in/reloader/init.lua:142: Failed to reload 'doom.modules.config.doom-tree' module
[ERROR Пт 22 апр 2022 13:13:29] ....config/nvim/lua/doom/modules/built-in/reloader/init.lua:142: Failed to reload 'doom.modules.config.doom-trouble' module
[ERROR Пт 22 апр 2022 13:13:29] ....config/nvim/lua/doom/modules/built-in/reloader/init.lua:142: Failed to reload 'doom.modules.config.doom-zen' module
[ERROR Пт 22 апр 2022 13:13:29] ....config/nvim/lua/doom/modules/built-in/compiler/init.lua:7: Doom compiler needs toggleterm plugin, please uncomment the 'terminal' entry in your doom_modules.lua
[ERROR Пт 22 апр 2022 13:13:29] ...x/.config/nvim/lua/doom/modules/built-in/runner/init.lua:7: Doom runner needs toggleterm plugin, please uncomment the 'terminal' entry in your doom_modules.lua
```

### End log dump
</details>

**Comment by connorgmeehan** [comment]
Stale, closed due to inactivity.  If this issue is still happening on `v4.x` post a comment and I'll re-open :)
