### ISSUE TITLE
Lua error when running Python code

### ISSUE THREAD

**Issue by pfassina** [NTBBloodbath/doom-nvim#318]
New to vim and doom-vim, so forgive me if I'm doing something wrong.

That being said, when I try to run a python file with code runner (`spc-c-r`), I get the following error:
`[doom] Î[string ":lua"]:1: in main chunk`.
Running the code through vim command (`:w !python`) works fine though.

**Comment by connorgmeehan** [comment]
Stale, closed due to inactivity.  If this issue is still happening on `v4.x` post a comment and I'll re-open :)
