### ISSUE TITLE
netrw hanging of window

### ISSUE THREAD

**Issue by Mremmalex** [NTBBloodbath/doom-nvim#320]
when trying to move to the file tree window with <leader> wh 
doom-vim freezes and won't move
![Screenshot from 2022-04-30 19-39-14](https://user-images.githubusercontent.com/40169444/166120156-36fbff2e-16ea-4e5f-b65d-916693aa754e.png)

**Comment by connorgmeehan** [comment]
Stale, closed due to inactivity.  If this issue is still happening on `v4.x` post a comment and I'll re-open :)
