### ISSUE TITLE
[BUG] (next) 93b558a breaks keymap like gd/gi/gr/<leader>cf

### ISSUE THREAD

**Issue by NextAlone** [NTBBloodbath/doom-nvim#328]
### Logs
```
E5108: Error executing lua [string ":lua"]:1: attempt to index field 'nest' (a nil value)
stack traceback:
        [string ":lua"]:1: in main chunk
Press ENTER or type command to continue
```

**Comment by NextAlone** [comment]
> I just had a go reproducing it but `gd`, `gi`, `<leader>cf` are all working for me. Can you provide some info on your environment and also ensure that you've deleted the `packer_compiled.lua` file/are not using impatient?

it fails also in a clean `next` branch clone

**Comment by NextAlone** [comment]
https://user-images.githubusercontent.com/12210746/168106458-434db576-8f7b-4230-9b3b-846456918825.mp4

**Comment by NextAlone** [comment]
> I just had a go reproducing it but `gd`, `gi`, `<leader>cf` are all working for me. Can you provide some info on your environment and also ensure that you've deleted the `packer_compiled.lua` file/are not using impatient?

Neovim: 0.7.0-3
Arch Linux: Linux next 5.17.5-arch1-1 #1 SMP PREEMPT Wed, 27 Apr 2022 20:56:11 +0000 x86_64 GNU/Linux

**Comment by NextAlone** [comment]
And follows this error when reload

![image](https://user-images.githubusercontent.com/12210746/168443408-c8a92a74-e565-4c89-9f7c-f43949258002.png)

**Comment by connorgmeehan** [comment]
@NextAlone Thank you for the info this has been resolved :). (`ce779b7ef7f140b4fe09e111b92c3ef29ff27589`)  Can you let me know if this works for you and then I'll close the issue :)

**Comment by NextAlone** [comment]
> @NextAlone Thank you for the info this has been resolved :). (`ce779b7ef7f140b4fe09e111b92c3ef29ff27589`)  Can you let me know if this works for you and then I'll close the issue :)

OK，i will test it later.

**Comment by NextAlone** [comment]
@connorgmeehan As i tested, it works fine. Thanks for your work.
