### ISSUE TITLE
file name does not show in the find file or telescope 

### ISSUE THREAD

**Issue by Mremmalex** [NTBBloodbath/doom-nvim#34]
when  i launch the find file, the name does not show on the files returned and is having indexing problems 
![2021-07-10-112840_1366x768_scrot_000](https://user-images.githubusercontent.com/40169444/125171587-ea82d780-e1ac-11eb-8daa-1c482d1704d1.png)

**Comment by NTBBloodbath** [comment]
Hey, thank you for reporting this and sorry for the delay (my net was really slow)!

It should be fixed now, let me know if the issue persists so we can re-open this issue.

Regards
