### ISSUE TITLE
LaTeX?

### ISSUE THREAD

**Issue by Martin-2019** [NTBBloodbath/doom-nvim#352]
Dear Maintainer!

How to use - configure LaTeX in Your excellent configuration?

M.

**Comment by connorgmeehan** [comment]
Stale, closed due to inactivity.  Anyone needs latex on `v4.x` post a comment and I'll re-open :) I don't have any experience with latex so some good plugin advice would be appreciated.

**Comment by justchokingaround** [comment]
i am interested, but also have no experience with latex

**Comment by justchokingaround** [comment]
done some research, the "lervag/vimtex" alongside "neoclide/coc-vimtex" seem to be what's best for latex in nvim
