### ISSUE TITLE
[BUG] nvim unusable for bigger git repositories

### ISSUE THREAD

**Issue by baurmatt** [NTBBloodbath/doom-nvim#358]
### Current Behavior:
nvim extremly lags when opening files in big repositories. I've stumbled over this when opening a file in the Gitlab repository. nvim/code is show after minutes.

### Expected Behavior:
nvim opens without delay

### Steps To Reproduce:
```bash
1. Install nvim with doom-nvim
2. https://gitlab.com/gitlab-org/gitlab.git
3. cd gitlab
4. nvim lib/gitlab/database/load_balancing/connection_proxy.rb
```

### Logs

<details>
<summary>Check Health Output</summary>

nvim: health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='iTerm.app'
  - INFO: $COLORTERM='truecolor'

nvim-lsp-installer: require("nvim-lsp-installer.health").check()
========================================================================
## nvim-lsp-installer report
  - OK: neovim version >= 0.6.0
  - WARNING: **Composer**: not available
  - WARNING: **julia**: not available
  - OK: **tar**: `bsdtar 3.5.1 - libarchive 3.5.1 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.8 `
  - OK: **gzip**: `Apple gzip 353.100.22`
  - OK: **curl**: `curl 7.79.1 (x86_64-apple-darwin21.0) libcurl/7.79.1 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.11 nghttp2/1.45.1`
  - OK: **wget**: `GNU Wget 1.21.3 built on darwin21.3.0.`
  - OK: **python3**: `Python 3.9.13`
  - OK: **node**: `v18.4.0`
  - OK: **Ruby**: `ruby 2.5.8p224 (2020-03-31 revision 67882) [-darwin21]`
  - OK: **bash**: `GNU bash, version 5.1.16(1)-release (aarch64-apple-darwin21.1.0)`
  - OK: **sh**: `Ok`
  - OK: **Go**: `go version go1.18.3 darwin/arm64`
  - OK: **PHP**: `PHP 8.1.7 (cli) (built: Jun  9 2022 14:08:46) (NTS)`
  - OK: **java**: `Ok`
  - OK: **javac**: `javac 18.0.1`
  - OK: **npm**: `8.12.1`
  - OK: **pip3**: `pip 22.1.1 from /opt/homebrew/lib/python3.9/site-packages/pip (python 3.9)`
  - OK: **RubyGem**: `3.0.9`

nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.6 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v18.4.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `/opt/homebrew/bin/gcc-11` executable found. Selected from { "/opt/homebrew/bin/gcc-11", "cc", "gcc", "clang", "cl", "zig" }
    Version: gcc-11 (Homebrew GCC 11.3.0_2) 11.3.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - toml           ✓ ✓ ✓ ✓ ✓ 
  - lua            x x x x x 
  - yaml           ✓ ✓ ✓ ✓ ✓ 
  - python         ✓ ✓ ✓ ✓ ✓ 
  - norg           ✓ . ✓ . ✓ 
  - dockerfile     ✓ . . . ✓ 
  - hcl            ✓ . ✓ ✓ ✓ 
  - bash           ✓ ✓ ✓ . ✓ 
  - go             ✓ ✓ ✓ ✓ ✓ 
  - ruby           ✓ ✓ ✓ ✓ ✓ 
  - json           ✓ ✓ ✓ ✓ . 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

## The following errors have been detected:
  - ERROR: lua(highlights): ...im/0.7.0/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 503
  - ERROR: lua(locals): ...im/0.7.0/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 15
  - ERROR: lua(folds): ...im/0.7.0/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 92
  - ERROR: lua(indents): ...im/0.7.0/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 29
  - ERROR: lua(injections): ...im/0.7.0/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid field at position 18

provider: health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 3 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - WARNING: Could not load Python 3:
    /opt/homebrew/bin/python3 does not have the "neovim" module.
    python3.10 not found in search path or not executable.
    /opt/homebrew/bin/python3.9 does not have the "neovim" module.
    python3.8 not found in search path or not executable.
    python3.7 not found in search path or not executable.
    /opt/homebrew/bin/python does not have the "neovim" module.
    - ADVICE:
      - See :help |provider-python| for more information.
      - You may disable this provider (and warning) by adding `let g:loaded_python3_provider = 0` to your init.vim
  - INFO: Executable: Not found

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.5.8p224 (2020-03-31 revision 67882) [-darwin21]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.
      - You may disable this provider (and warning) by adding `let g:loaded_ruby_provider = 0` to your init.vim

## Node.js provider (optional)
  - INFO: Node.js: v18.4.0
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim
      - You may disable this provider (and warning) by adding `let g:loaded_node_provider = 0` to your init.vim

## Perl provider (optional)
  - WARNING: "Neovim::Ext" cpan module is not installed
    - ADVICE:
      - See :help |provider-perl| for more information.
      - You may disable this provider (and warning) by adding `let g:loaded_perl_provider = 0` to your init.vim

vim.lsp: require("vim.lsp.health").check()
========================================================================
  - INFO: LSP log level : WARN
  - INFO: Log path: /Users/mbaur/.cache/nvim/lsp.log
  - INFO: Log size: 1575 KB

vim.treesitter: require("vim.treesitter.health").check()
========================================================================
  - INFO: Runtime ABI version : 14
  - OK: Loaded parser for bash: ABI version 13
  - OK: Loaded parser for dockerfile: ABI version 13
  - OK: Loaded parser for go: ABI version 13
  - OK: Loaded parser for hcl: ABI version 13
  - OK: Loaded parser for json: ABI version 13
  - OK: Loaded parser for lua: ABI version 13
  - OK: Loaded parser for norg: ABI version 13
  - OK: Loaded parser for python: ABI version 13
  - OK: Loaded parser for ruby: ABI version 13
  - OK: Loaded parser for toml: ABI version 13
  - OK: Loaded parser for yaml: ABI version 13

which_key: health#which_key#check
========================================================================
## WhichKey: checking conflicting keymaps
  - WARNING: conflicting keymap exists for mode **"n"**, lhs: **"gc"**
  - INFO: rhs: `<Plug>kommentary_motion_default`

</details>

<details>
<summary>Doom Report Output</summary>
# Doom Nvim crash report

> Report date: 2022-07-15 13:43:37

## System and Doom Nvim information

- **OS**: Darwin
- **Neovim version**: 0.7.0
- **Doom Nvim information**:
  - **version**: 3.3.0
  - **`doom_root` variable**: `/Users/mbaur/.config/nvim`
  - **`doom_configs_root` variable**: `/Users/mbaur/.config/nvim`

### Begin error log dump

```

```

### End log dump
</details>

### Anything else:
Others stumbled over this as well -> https://github.com/LunarVim/LunarVim/issues/1337

Solution might be to switch from galaxyline to statusline.

**Comment by connorgmeehan** [comment]
Hi Baurmatt, I think this will be resolved with the [doom-nvim re-write](https://github.com/NTBBloodbath/doom-nvim/tree/next) where we switch to using heirline.  You can try it out quickly via the single line installer bash script (in the readme) which will move your old `~/.config/nvim` to `~/.config/nvim-old`.  Let me know if this works for you.

**Comment by baurmatt** [comment]
@connorgmeehan Thanks! Is there a ~ planned stable release date? Or, to phrase it differently, what stability has the re-write reached?

**Comment by connorgmeehan** [comment]
It's been delayed for ages but the final release should be in the next week or two.  All that's left is updating the `:h doom-nvim` docs (I'm just a little stretched for time right now).  However, there shouldn't be any breaking changes before then and, to be honest, this branch is probably more stable than main right now due to plugin updates/deprecated warning fixes.  I haven't had a chance to test on linux but it should work the same as macos.

**Comment by baurmatt** [comment]
@connorgmeehan Thanks! Do you already want bug reports for errors I'm running into?

btw: Yes, the problem mentioned in the ticket has been fixed by the re-write 🥳

**Comment by connorgmeehan** [comment]
Yes please! That'd be very helpful!

**Comment by baurmatt** [comment]
Done :) Thanks for all the help! :)
