### ISSUE TITLE
[BUG][next] Disabling numbering isn't supported anymore

### ISSUE THREAD

**Issue by baurmatt** [NTBBloodbath/doom-nvim#359]
### Current Behavior:
"next" version of doom-nvim doesn't supports disabling numbering

```
    -- Set numbering
    -- false : Enable  number lines
    -- true  : Disable number lines
    -- @default = false
    disable_numbering = false,

    -- Set numbering style
    -- false : Shows absolute number lines
    -- true  : Shows relative number lines
    -- @default = true
    relative_num = true,
```

### Expected Behavior:
Supports disabling numbering

### Logs

<details>
<summary>Check Health Output</summary>

</details>

<details>
<summary>Doom Report Output</summary>

</details>

### Anything else:

**Comment by connorgmeehan** [comment]
Fixed in https://github.com/NTBBloodbath/doom-nvim/commit/1f5c51e8534126a9662386239d9a20eec3c12131 :)
