### ISSUE TITLE
[BUG][next] max_columns not working anymore

### ISSUE THREAD

**Issue by baurmatt** [NTBBloodbath/doom-nvim#360]
### Current Behavior:
`max_columns` isn't working anymore on "next"

### Expected Behavior:
`max_columns` works.

```
     -- Set max cols
     -- Defines the column to show a vertical marker
     -- @default = 80
     max_columns = 80,
```

### Logs

<details>
<summary>Check Health Output</summary>

</details>

<details>
<summary>Doom Report Output</summary>

</details>

**Comment by connorgmeehan** [comment]
This is fixed in https://github.com/NTBBloodbath/doom-nvim/commit/9bc7b8a24eadb275a794a9e2eab78655ce92f9c9 (I also added the ability to set `doom.max_columns = false` to disable it).
