### ISSUE TITLE
[BUG][next] mouse isn't possible to disable

### ISSUE THREAD

**Issue by baurmatt** [NTBBloodbath/doom-nvim#366]
### Current Behavior:
Mouse is configured to `vim.opt.mouse = "a"`. Seems like I can unset in config.lua.

### Expected Behavior:
I really really really like to have `vim.opt.mouse = false` 😂 

### Logs

<details>
<summary>Check Health Output</summary>

</details>

<details>
<summary>Doom Report Output</summary>

</details>

**Comment by connorgmeehan** [comment]
I had a play around with it, it looks like this can be achieved by setting `vim.opt.mouse = ''` in `config.lua`.  I don't want to add too many more wrappers around nvim native apis because it just adds more code to maintain.  Let me know if this works for you and if not I'll re-open :).
