### ISSUE TITLE
Can't figure out new custom plugin location

### ISSUE THREAD

**Issue by will** [NTBBloodbath/doom-nvim#37]
I'm probably missing something really basic here, but when I try having plugins.lua be

```lua
return {
  "dense-analysis/ale",
}
```
or

```lua
return {
  {"dense-analysis/ale"},
}
```

I get this when starting nvim
```
packer.nvim] [ERROR 20:33:11] async.lua:20: Error in coroutine: .../site/pack/packer/opt/packer.nvim/lua/packer/display.lua:784: Vim(lua):E5108: Error executing lua [string ":
lua"]:1: attempt to index global 'Luasnip_current_nodes' (a nil value)
```

**Comment by NTBBloodbath** [comment]
Hey, it looks like an error caused by `LuaSnip`. Is it installed? You can check it by doing `:PackerStatus` and looking for a `LuaSnip` entry

**Comment by NTBBloodbath** [comment]
So I've did a temporal fix for this behavior because it's a problem of `LuaSnip`. Please follow the steps that are listed in the issue #38 for fixing it.

Let me know if the issue persists for you.

Regards

**Comment by will** [comment]
Deleting LuaSnip and having it get reinstalled fixed it. Thank you!
