### ISSUE TITLE
[BUG] `explorer` module breaks randomly

### ISSUE THREAD

**Issue by connorgmeehan** [NTBBloodbath/doom-nvim#374]
### Current Behavior:
Unable to re-create reliably but something is causing the `<leader>oe` keybind to break during regular use.

### Expected Behavior:
Always able to open/close file explorer.

**Comment by edwintorok** [comment]
`<leader>oe` calls `Lexplore%s`, a typo?

 `netrw`  defines an `Lexplore` command, however `netrw` is disabled by default.
If I disable `explorer` feature, but enable `netrw` then the command works.

Looks like there is a duplicate keybinding defined in `core/init.lua` (conditional on explorer being enabled) and `explorer/init.lua`
