### ISSUE TITLE
Font requirements

### ISSUE THREAD

**Issue by bdillahu** [NTBBloodbath/doom-nvim#39]
I may have just missed something, but wanted to point this out.

Running on MacOSX with iTerm as the terminal. I had to switch my terminal font preferences to FiraCode Nerd Font Mono (the important part being the Nerd I believe) to get the various little icons and things to show up.

I had the font loaded, but this wasn't my default font.

**Comment by NTBBloodbath** [comment]
Hey, the Nerd fonts are needed to display some icons as you've said (that's completely optional IMO but it improves the UI). Maybe I'm misunderstanding you (let me know if that's the case!) but you can take a look at [nerd-fonts repo](https://github.com/ryanoasis/nerd-fonts/) to see if they have your previous font too and use it instead of FiraCode.

**Comment by bdillahu** [comment]
Understand... I was mostly just pointing out that it seems to be a requirement/pre-req to have your terminal supporting said font and I hadn't noticed it in the Getting Started documents. I knew how to fix it, but to forestall other confusion, thought I would mention it.

**Comment by NTBBloodbath** [comment]
Oh, so there are terminals that doesn't support these fonts? Being honest didn't knew about that!

Maybe _if you want and have the time to_ can we add a Troubleshooting section in the wiki for this behavior? I think this can be useful for others too.

**Comment by bdillahu** [comment]
Well, I probably worded that wrong, but your terminal may not have that font loaded/in use (at least mine didn't). Of course there are probably some that don't have them supported at all, I don't know. I'll look at the Wiki and see.

**Comment by NTBBloodbath** [comment]
Oh I think I have completely understood what you tell me. Yeah, the installer only downloads the font and refresh the fonts cache but it doesn't automatically apply it to your terminal _and I don't think that it should be automatically applied_. Definitely we should document it somewhere.

**Comment by NTBBloodbath** [comment]
Also thank you for pointing this behavior to me and editing the wiki!

I think we should close this now.

**Comment by NTBBloodbath** [comment]
@all-contributors add @bdillahu for documentation
