### ISSUE TITLE
Minimap doesn't seem to toggle

### ISSUE THREAD

**Issue by bdillahu** [NTBBloodbath/doom-nvim#44]
Have it on in config... :PackerStatus shows it loaded, but then it says MinimapToggle not found...

My goof or a bug?

**Comment by NTBBloodbath** [comment]
Hey, as the [self-documentation](https://github.com/NTBBloodbath/doom-nvim/blob/main/doomrc.lua#L34) says, the minimap plugins depends on [wfxr/code-minimap](https://github.com/wfxr/code-minimap) to work :slightly_smiling_face:

**Comment by bdillahu** [comment]
Well, saw that, but sorry, was unclear to me that it was a separate thing and not a plugin that would auto-load... so after installing it, yes it works...

Thanks!

**Comment by NTBBloodbath** [comment]
no worries, glad to help you!
