### ISSUE TITLE
node modules are included in telescope

### ISSUE THREAD

**Issue by Mremmalex** [NTBBloodbath/doom-nvim#45]
node-mudeles are included when find files is launched can it be turned off

**Comment by NTBBloodbath** [comment]
Hey, not actually, at least not in the Doom configuration files. But I think you can temporarily modify the `lua/doom/modules/config/doom-telescope.lua` file locally and add it to the `file_ignore_patterns` table in the Line 30.

So after modifying it, it should look like `file_ignore_patterns = { 'node_modules' }`.

I'll leave this issue open until we add a custom option in the `doom_config.lua` file to ignore custom patterns in `telescope.nvim`.

**Comment by Mremmalex** [comment]
alright, the work around works for  me, thanks

**Comment by NTBBloodbath** [comment]
I'll close this for now since I introduced some sane defaults for the telescope ignored patterns in the development version and I want to keep a track of what's left for releasing the next version with these changes 🙂
