### ISSUE TITLE
Feature request: Debugging tools

### ISSUE THREAD

**Issue by NTBBloodbath** [NTBBloodbath/doom-nvim#46]
Adding tools for debugging could be very useful.

We could use [nvim-dap] + [nvim-dap-ui] in combination with [DAPInstall.nvim] to achieve a good and automated integration similar to what is currently available with the Language Servers Protocol.

[nvim-dap]: https://github.com/mfussenegger/nvim-dap
[nvim-dap-ui]: https://github.com/rcarriga/nvim-dap-ui
[DAPInstall.nvim]: https://github.com/Pocco81/DAPInstall.nvim

**Comment by Pocco81** [comment]
I think it's also worth taking a look at: 

* https://github.com/nvim-telescope/telescope-dap.nvim
* https://github.com/theHamsta/nvim-dap-virtual-text

**Comment by bavalpey** [comment]
Would be amazing if you could add an object explorer for languages that support it (I'm thinking something like the Jetbrains IDE for Python allows one to explore defined objects at breakpoints).  I'm not sure if there's a debugging plugin that does this for neovim...  But it is amazing.

**Comment by starptr** [comment]
Also take a look at https://github.com/puremourning/vimspector. Although neovim isn't fully supported, I use it regularly for c++ and Rust debugging

**Comment by Pocco81** [comment]
Hey @starptr! I don't do any C++ or Rust dev, so correct me if I'm wrong but... there are some very cool cpp and Rust debuggers on [this list](https://microsoft.github.io/debug-adapter-protocol/implementors/adapters/) that should be supported by [nvim-dap](https://github.com/mfussenegger/nvim-dap). Maybe you should consider giving them a try?

Furthermore, [DAPInstall.nvim](https://github.com/Pocco81/DAPInstall.nvim) already supports two debuggers for C++ and Rust dev (haven't been tested yet) as shown in [this list](https://github.com/Pocco81/DAPInstall.nvim#list-of-debuggers). Give them a try!

**Comment by NTBBloodbath** [comment]
I'm gonna close this one because we have already implemented it in the development branch (v3.1 testing). Hopefully we can merge it soon :)
