### ISSUE TITLE
Override default mappings

### ISSUE THREAD

**Issue by LoricAndre** [NTBBloodbath/doom-nvim#48]
Hi,
I switched to doom-nvim from my config and I'm missing some mappings, such as mapping `<leader><space>` to `:b#`
Simply adding them to `doom_config.lua` is not enough right now, and I think it should be (I had to uncomment the mapping in the config)

**Comment by NTBBloodbath** [comment]
Hey, all our mappings has the `noremap` flag. That should explain why you can't replace them by using the `doom_config.lua`.

At the moment the only solution for overriding them is by commenting the defaults in the keybindings file as you've did. Maybe we should add an option in our `doom_config.lua` to allow overriding the default mappings? :thinking:

**Comment by LoricAndre** [comment]
Another way to do this might be to set the mappings in `doom_config.lua` as noremap, or at least allow them to be. To be honest, I wasn't using normal mappings in my old config either.

**Comment by NTBBloodbath** [comment]
Hey, sorry for the delay. A lot of good stuff happened in the development branch (hopefully I'll be able to release the new version the next week _if we don't have more things to do_), mainly regarding to how mappings works.

Basically you can now enable the option to override the default keymappings (it's enabled by default btw) in your `doom_config.lua` file and add your own options for your own keymappings too :slightly_smiling_face:
