### ISSUE TITLE
Modifying config file make plugins useable (?)

### ISSUE THREAD

**Issue by pcapiod** [NTBBloodbath/doom-nvim#51]
**Context**
Hi,

Thanks a lot for this very good project! I loved trying to tweak it a bit. One thing that I have noticed is when I am opening the config files, plugins become unavailable.
One way to reproduce it on my machine is to open a config file (doom_config or doomrc for instance) from the start page via the recent file list. I cannot use telescope anymore afterwards or when I save a change in those config files, the FormatWrite function is called (I have auto format on 'true") and an error is displayed.

Second thing, :DoomUpdate does not work, the read() function is calling an error

**Process**
- Open doom-nvim
- Open a config file from start screen, from recent file list
- Do some modification, save... then error, <leader>ff does not work, etc...
- Plugins are not available anymore on other buffers as well !

**Version**
3.0.6
Terminal : Kitty, nvim 0.5.0
Distro : Manjaro KDE (updated)

In addition, what are the key bindings for the kommentary plugin?

If you need more info, please let me know!

**Comment by NTBBloodbath** [comment]
Hey, thank you for providing that useful information!

> I cannot use telescope anymore afterwards

Sadly I can't reproduce it on my machine :(, maybe your configs has a bad value or a syntax error and these things are causing issues? Idk

> when I save a change in those config files, the FormatWrite function is called (I have auto format on 'true") and an error is displayed.

I can reproduce this one, it's maybe a lazy-loading issue. I think I can fix it quickly.

> :DoomUpdate does not work, the read() function is calling an error

It is working fine for me, can you please send the error that you're getting? Maybe the `[ERROR]` entries of the `~/.local/share/nvim/doom.log` file can be useful

> In addition, what are the key bindings for the kommentary plugin?

They're documented in `:h doom_nvim_commands_keybindings` at the end.

- `gcc` for comenting in NORMAL mode
- `gc` for comenting in VISUAL mode

**Comment by pcapiod** [comment]
> Sadly I can't reproduce it on my machine :(, maybe your configs has a bad value or a syntax error and these things are causing issues? Idk
I just installed the Doom-nvim on another machine and I have the same error, could be due to the OS? but that would be very strange. I guess that error could come from the issue with the lazy-load.
I am not sure how to tweak the lazy-loading?  

> It is working fine for me, can you please send the error that you're getting? Maybe the [ERROR] entries of the ~/.local/share/nvim/doom.log file can be useful
Unfortunately, nothing is written in the doom.log for that error, here is a copy of it:

`E5108: Error executing lua /path/to/doom/core/functions/init.lua:197: bad argument #1 to 'read' (invalid option)`

> They're documented in :h doom_nvim_commands_keybindings near to the end of the section.
Great, thank you !

**Comment by jakethagle** [comment]
As another data point I was also able to repro this on a fresh install on macOS Big Sur
Steps to repro were:
- Fresh install of neovim 
- Fresh install of doom-nvim
- Change the config for format_on_save to true

**Comment by pcapiod** [comment]
> Sadly I can't reproduce it on my machine :(, maybe your configs has a bad value or a syntax error and these things are causing issues? Idk

Ok I can add more on this. I could replicate this issue every single time by doing this:
- Open doom-nvim
- Open a config file (e.g. `doom_config.lua`)
- Save (`:w`)
- Open telescope (`<leader>ff`) -> Error (`Not a command editor`)

**Comment by NTBBloodbath** [comment]
Alright so I was finally able to reproduce that telescope issue, I'll dig on it right now. Thank you!

The formatter error was already fixed so it shouldn't be causing more issues.

And about the `:DoomUpdate` command, I can't reproduce it but I'll keep trying to!

Regards

**Comment by NTBBloodbath** [comment]
Hmm I was not able to reproduce the telescope issue again nor the `:DoomUpdate` one. Let me know if these issues persists for you right now so we can try to debug them.

**Comment by pcapiod** [comment]
> Hmm I was not able to reproduce the telescope issue again nor the :DoomUpdate one. Let me know if these issues persists for you right now so we can try to debug them.

The telescope issue seems fixed. I cannot reproduce it.

The `:DoomUpdate` issue is still there.
The error points to this line 
`local git_branch = branch_handler:read('a'):gsub('[\r\n]', '')`
in `core/functions/init.lua`

**Comment by NTBBloodbath** [comment]
Hmm that's strange, is your `~/.config/doom-nvim` a git repository?

**Comment by pcapiod** [comment]
> Hmm that's strange, is your ~/.config/doom-nvim a git repository?

Sorry for the late answer. I have tested by removing Doom-nvim completely and reinstalling from the `curl` command on a Manjaro KDE, on a Ubuntu VM 18.04, and on a WSL Ubuntu 20.04. `DoomUpdate` does not work on the Manjaro machine but works on both Ubuntu machines.

**Comment by NTBBloodbath** [comment]
Hmm that's interesting, thank you for doing these tests!

Does it work in the Ubuntu instances when using `'*a'`? If that's the case then we should use the old format to avoid having weird issues :thinking:

**Comment by pcapiod** [comment]
> Does it work in the Ubuntu instances when using '*a'? If that's the case then we should use the old format to avoid having weird issues 🤔

It works on my end with `'*a'`
