### ISSUE TITLE
Version 3.0.7 fresh install does not work

### ISSUE THREAD

**Issue by bavalpey** [NTBBloodbath/doom-nvim#54]
I updated doom using :DoomUpdate, but then running neovim afterwards broke neovim.
I tried to reinstall, clearing the old configuration (and the plugins), but it results in an error.
There also seems to be a bug in the bash installation script, where the colors that should be output to the terimal are not done properly (this isn't an issue I care about, but it could be related?)

<details><summary>Here's an example of what I mean</summary>
.74m[+] Trying to clone doom-nvim ...
.72m[✔] Successfully cloned doom-nvim, some demons were released in your terminal!
.72m[✔] Installed Doom Nvim and some demons were released, be careful!
.74m[+] Checking requirements
.72m[✔] Check requirements : git version 2.17.1
.72m[✔] Check requirements : nvim
.72m[✔] Check requirements : node
.72m[✔] Check requirements : npm

.72m==================================================
.72m   You are almost done. Start neovim to install
.72m         the plugins and kill some demons.
.72m
.72m Thanks for installing Doom Nvim. If you have any
.72m            issue, please report it :)
.72m==================================================
</details>

Then, following the installation via the command line provided in the readme, I try to run neovim via nvim command, which resulted in the following error
```
E5113: Error while calling lua chunk: /home/bavalpey/.config/nvim/init.lua:20: attempt to index field 'opt' (a nil value)
Error detected while processing function bufferline#enable[32]..bufferline#highlight#setup[8]..<SNR>24_fg:
line    2:
E5555: API call: Invalid highlight name: Special
line    3:
E715: Dictionary required```

**Comment by NTBBloodbath** [comment]
Hey!

> There also seems to be a bug in the bash installation script, where the colors that should be output to the terimal are not done properly (this isn't an issue I care about, but it could be related?)

It's not related to this issue, but I'll surely dig on it too, thank you for reporting it.

> I try to run neovim via nvim command, which resulted in the following error

I've experienced it only one time while doing a fresh install, but the error was gone after installing the plugins. However it seems to be a `nvim-bufferline.lua` plugin error. Can you open Neovim and run `PackerSync` and reboot after the command finishes?

**Comment by bavalpey** [comment]
Hmm.. I tried to run :PackerSync but it seems the plugin error is causing issues with loading any plugin.  The :PackerSync command does not work, with Neovim saying E492: Not an editor command: PackerSync.  None of the packer commands work, actually...

**Comment by NTBBloodbath** [comment]
Hmm is your Neovim up-to-date? This `attempt to index field 'opt' (a nil value)` shouldn't happen.

Also, did you tried removing all the plugins including packer and then restarting Neovim?

`rm -rf ~/.local/share/nvim/site/pack/packer/*`

If this one doesn't work then let's source the packer setup file manually to get it working.

`nvim ~/.config/doom-nvim/lua/doom/modules/init.lua`

and then inside Neovim, we will source the file by doing `:source %` and then we should be able to run `:PackerSync`.

**Comment by bavalpey** [comment]
My neovim version is the same I had been using previously -- NVIM v0.5.0-dev.

I tried removing all plugins (including packer) and restarted Neovim.  I no longer run into most of the errors.  However, I do still receive the first error
E5113: Error while calling lua chunk: /home/bavalpey/.config/nvim/init.lua:20: attempt to index field 'opt' (a nil value)


When I try to run :source % on the lua file, I get errors saying the lines are not editor commands (is there something different I must do to source lua files within neovim?)

**Comment by NTBBloodbath** [comment]
> My neovim version is the same I had been using previously -- NVIM v0.5.0-dev.

Please consider updating to the 0.5 stable, maybe the nightly version that you're running is missing features.

**Comment by NTBBloodbath** [comment]
Glad to help :)
