### ISSUE TITLE
Module 'lspinstall' not found

### ISSUE THREAD

**Issue by Silipwn** [NTBBloodbath/doom-nvim#55]
I've been seeing this issue for sometime while checking this project out, I'm not exactly sure how this is triggered. I've tried setup everything 4 times, and I usually end up at this error. 

I manage to get everything installed but on reload, this comes up.
```
Error executing vim.schedule lua callback: /home/silipwn/.config/nvim/lua/doom/core/config/init.lua:421: module 'lspinstall' not found:                                     
        no field package.preload['lspinstall']                                        
        no file './lspinstall.lua'
.....
```
Is there something I'm missing to configure? 

When I run `ls ~/.local/share/nvim/site/pack/packer/start/` :

`neogit	vim-header`

### Version details: 
`nvim`: v0.6.0-dev+12-gf515baedc
`doom-nvim`: v3.0.7

**Comment by NTBBloodbath** [comment]
Hey, that's really strange for me because of

1. The error line is pointing to a comment :confused:
2. The function that triggers `lspinstall` in that file doesn't try to load that plugin if the plugin is not installed nor loaded

Can you please send the output of `ls ~/.local/share/nvim/site/pack/packer/opt/nvim-lspinstall` and check if lspinstall is there when you do `PackerStatus`?

**Comment by jakethagle** [comment]
I was also able to repro this. I confirmed nvim-lspinstall existed in the path you asked for.

**Comment by lavixta** [comment]
I have the same issue, but as i moved or remove ~/.local/share/nvim/site/pack/packer/  to another file and reinstall doom-nvim. The problem solve

**Comment by Silipwn** [comment]
I was temporarily able to fix it by removing everything inside `packer` directory. 
`rm -rf ~/.local/share/nvim/site/pack/packer/`.

**Comment by Silipwn** [comment]
Yeah, I guess we can close this for now. If someone else is able to reproduce it, they can refer to the fix above. I hope it worked for @jakethagle as well.

**Comment by jakethagle** [comment]
I have more info on this. I managed to repro it by updating the languages in my doomrc to include a new one to be installed for lsp. Upon restarting doom-nvim I got this stack trace. By doing an `rm -rf ~/.local/share/nvim/lspinstall` I was able to resolve my issue and it reinstalled all of the correct language servers.
