### ISSUE TITLE
Defining Custom Keybindings in doom_config.lua causes error

### ISSUE THREAD

**Issue by bavalpey** [NTBBloodbath/doom-nvim#57]
I was trying to map <MiddleMouse> to be <Nop> in the mappings field of doom_config.lua.  However, when I populate the mappings field of doom_config.lua, it reports an error on next launch of neovim.

I tried to use the example provied in the doom_config.lua for this section.  However, even copy pasting that example causes the same error.

I tried the following configuration in the mappings section of the local nvim section.

```lua
mappings = {
    {'n', '<MiddleMouse>', '<Nop>'},
    {'i', '<MiddleMouse>', '<Nop>'}, 
}
```

When launching nvim, this results in the following error:
```
Error executing vim.schedule lua callback: /home/bvalpey/.config/nvim/lua/doom/core/functions/init.lua:70: attempt to call local 'map' (a table value)
```

It's possible that I am doing something wrong with the syntax.  However, I also tried the provided example, which resulted in the same error.

**Comment by NTBBloodbath** [comment]
Hey, is your doom-nvim up-to-date? Someone reported this issue too in Reddit and I've already fixed it. You can update by using `:DoomUpdate`. Let me know if the issue persists for you.

**Comment by NTBBloodbath** [comment]
Hey, is your doom-nvim up-to-date? Someone reported this issue too in Reddit and I've already fixed it. You can update by using `:DoomUpdate`. Let me know if the issue persists for you.

**Comment by bavalpey** [comment]
Yes, my Doom nvim is up to date (I reinstalled it today).  I just ran :DoomUpdate again to verify, but the issue persists.

**Comment by NTBBloodbath** [comment]
Hmm that's strange then, mine is working. Can you please check the line 70 that is causing the issue?

It was looking like this when there were issues:

```lua
map(map[1], map[2], map[3], opts)
```

And it should look like this with the issue fixed

```lua
utils.map(map[1], map[2], map[3], opts)
```
