### ISSUE TITLE
require "lspconfig"[diagnostic'].manager.try_add() 

### ISSUE THREAD

**Issue by lavixta** [NTBBloodbath/doom-nvim#59]
<img width="1440" alt="Screen Shot 2021-07-15 at 11 37 33 AM" src="https://user-images.githubusercontent.com/36840462/125729634-07b222f6-d33c-4946-8c20-edba66f557ea.png">
Hi, i just update Doom-nvim 3.0.7 and have this issue when i open *.lua file ( but not for other file types ), as i tried to fix it, when i remove "syntax on" line 56 and "packerLoad tree-sitter" the error disappear but my tree-sitter hightlight was gone too. How can it fix this 

OS: Mac OS big Sur
Nvim-version: 0.6.0

**Comment by NTBBloodbath** [comment]
Hmm I've encountered this issue too when using `diagnosticls`, the error was **only** with lua files. Thank you for providing that information, I'll dig on it later because I'll not be at home but I'll try to fix it ASAP.

**Comment by NTBBloodbath** [comment]
Hey, sorry for the delay.

Please try with a minimal config and see if diagnosticls works on it _if you need this language server_. If it does, then don't lazy load the native lsp in `lua/doom/modules/init.lua`.

**Comment by lavixta** [comment]
Ah, a little late response, but i noticed since it only happened when i open lua file so i go into doom-lspinstall and delete a case for lua server and everyrthing is normal now. But i have a question, why you set a special case for lua server ?
<img width="954" alt="Screen Shot 2021-07-20 at 10 58 48 PM" src="https://user-images.githubusercontent.com/36840462/126356760-67edd8d8-f702-4e4e-969b-78cefe25cc81.png">

**Comment by NTBBloodbath** [comment]
Hmm that's an strange behavior tbh

> why you set a special case for lua server ?

That's for adjusting sumneko (the Lua language server) to Neovim development so by example the `vim.` will be recognized and don't raise warning about undefined `vim`
