### ISSUE TITLE
Feature request: Add 'options' field to doom_config.lua

### ISSUE THREAD

**Issue by LoricAndre** [NTBBloodbath/doom-nvim#60]
It would be nice to be able to set custom options directly from `doom_config.lua`, for example through an `options` field !

**Comment by NTBBloodbath** [comment]
Hey, looks interesting. Can you please provide an example of what options can be there?

**Comment by LoricAndre** [comment]
I'd use it, for example, for `textwidth`, maybe `incsearch` or `shiftwidth` and friends

**Comment by NTBBloodbath** [comment]
gotcha, I think it's gonna be really useful!

**Comment by LoricAndre** [comment]
Do you want me to work on this ? I should be able to add it quickly, I might just not be familiar with where the doc might need to be updated

**Comment by NTBBloodbath** [comment]
Sure thing!

The vast majority of the code in the configuration files are self-documented so I think that it should be self-documented too :)
