### ISSUE TITLE
Break in the startup

### ISSUE THREAD

**Issue by ashincoder** [NTBBloodbath/doom-nvim#68]
Hi I have a breakage whilte starting doom-nvim here it is.

[![asciicast](https://asciinema.org/a/2XVtBXrsO2mJzjRNFVLQWQvbF.svg)](https://asciinema.org/a/2XVtBXrsO2mJzjRNFVLQWQvbF)

**Comment by NTBBloodbath** [comment]
Hey, that's an expected behavior because doom is loaded asynchronously.

**Comment by ashincoder** [comment]
But isn't it a litter annoying. And also that is recorded with asciinemma I will record with my real screen recorder

**Comment by ashincoder** [comment]
Ok it is fine.

**Comment by Akianonymus** [comment]
> Hey, that's an expected behavior because doom is loaded asynchronously.

You should load basic theme elements like bg before.

Also disable tilde and and intro message for more seamless startup

and make your theme a plugin and lazy load through packer ( for fully fixing the issue )
