### ISSUE TITLE
Fails to run properly; throws error

### ISSUE THREAD

**Issue by themaster567** [NTBBloodbath/doom-nvim#7]
I have all dependencies including the optional ones and am using the latest neovim nightly. When I go to run it, I get the following error:
```
E5113: Error while calling lua chunk: /home/killbotvii/.config/nvim/lua/doom/keybindings/init.lua:7: module 'which-k
ey' not found:
        no field package.preload['which-key']
        no file './which-key.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/luajit-2.1.0-beta3/which-key.lua'
        no file '/usr/local/share/lua/5.1/which-key.lua'
        no file '/usr/local/share/lua/5.1/which-key/init.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/which-key.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/which-key/init.lua'
        no file './which-key.so'
        no file '/usr/local/lib/lua/5.1/which-key.so'
        no file '/home/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/which-key.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
```
I have already tried to completely delete both the doom-nvim folder and anything related to nvim in the config folder and running the script again, but I get the same error.

**Comment by NTBBloodbath** [comment]
Hi, can you please run `:PackerStatus` and paste the output? There should be an entry called `which-key.nvim`, maybe the plugin wasn't installed correctly

**Comment by themaster567** [comment]
I ran it and got this in a window at the bottom
```
Error executing vim.schedule lua callback: vim/shared.lua:396: t: expected table, got nil
stack traceback:
        vim/shared.lua:396: in function 'tbl_count'
        ...ite/pack/packer/start/packer.nvim/lua/packer/display.lua:282: in function 'cb'
        vim.lua:253: in function <vim.lua:253>
```
Then a blank packer.nvim page.

**Comment by NTBBloodbath** [comment]
It's a bit weird, I need to know a few things to be able to debug it.

1. Where are you running Doom, in a container?

2. The path and content of `.local/share/nvim/site/pack/packer/start/`

**Comment by themaster567** [comment]
1. Nothing special in any way, I do not have any containers set up.

2. ```
ls ~/.local/share/nvim/site/pack/packer/start
packer.nvim
```

**Comment by NTBBloodbath** [comment]
There are no plugins installed apart from the plugin manager. Could you run `:PackerInstall` and check again if the error persists?

**Comment by themaster567** [comment]
Ran it and it then installed a massive amount of plugins, failing to install one called session-lens. Upon rebooting it, I'm now on the Doom NVIM page and it seems as though things are working now. Does that one plugin matter at all?

**Comment by NTBBloodbath** [comment]
> Ran it and it then installed a massive amount of plugins

Yes, Doom Nvim is made up of a large number of plugins. You can disable those that you are not going to use, in the [documentation] you can see how to do it.

> failing to install one called session-lens. Does that one plugin matter at all?

Not really, it's an extension for the session manager. Can be ignored if you won't use it.

[documentation]: https://github.com/NTBBloodbath/doom-nvim/blob/main/docs/getting_started.md#disabling-plugins

**Comment by themaster567** [comment]
I just feel the need to say that I'm not normally stupid and I feel bad if I just missed an instruction somewhere. I hope I wasn't wasting your time. I did go over the install instructions a few times and all it said to do was run the curl command and then open nvim. Did I miss something somewhere?

**Comment by NTBBloodbath** [comment]
> I hope I wasn't wasting your time.

Don't worry, you aren't disturbing me :slightly_smiling_face: 

> I did go over the install instructions a few times and all it said to do was run the curl command and then open nvim. Did I miss something somewhere?

No, you have followed all the installation steps. I modified a lot of files recently and forgot to add something to install required plugins at first start, I'm going to fix it right now. Thanks for pointing this out to me!

**Comment by themaster567** [comment]
Glad I could help!
