### ISSUE TITLE
how to add custom options to `doom_config.lua`

### ISSUE THREAD

**Issue by molleweide** [NTBBloodbath/doom-nvim#72]
Hi,

### None of these commands work for me in doom config. 
How do I do this right?

``` lua
	-- Set custom commands
	-- @default = {}
	-- example:
	--   {
	--      'echo "Hello, custom commands!"'
	--   }
	commands = {
	     { 
	        'echo "Hello, custom commands!"'
	     },
	    { 'vim.cmd[[ :set keymap=INSERT_COLEMAK ]]' },
	    { 'vim.cmd[[ :set iminsert=1 ]]' },
	    { 'vim.cmd[[ :set iminsert=0 ]]' },
	},
```

## it gives me this err
```
Error executing vim.schedule lua callback: ...k/cheovim/start/cheovim/lua/doom/core/functions/init.lua:60: Expected lua string
```

**Comment by NTBBloodbath** [comment]
Hey, can you please try removing the `vim.cmd[[ ... ]]` functions and leaving only the options (e.g. `set iminsert=1`)? Doom will automatically call that function for every custom command.

You can see this behavior [here](https://github.com/NTBBloodbath/doom-nvim/blob/main/lua/doom/core/functions/init.lua#L60)

Regards

**Comment by molleweide** [comment]
hmm wierd I though i tried what you mentionned first and it didn't work but now when i do it it works :P thanks dealing with my stupidity.
