### ISSUE TITLE
Problem add Tree-sitter playground plugin

### ISSUE THREAD

**Issue by lavixta** [NTBBloodbath/doom-nvim#73]
Hey, i think tree-sitter playground is very helpful for user to use tree-sitter. However i have a problem adding it in plugins.lua 
<img width="1440" alt="Screen Shot 2021-07-24 at 12 50 10 AM" src="https://user-images.githubusercontent.com/36840462/126821653-b69560ad-ab0d-48ff-b277-b120203cbf3e.png">
Nvim: 0.5.0
doom-nvim: 3.1.0
OS: Mac OS 
I tried install query and reinstall but do not know how to fix

**Comment by lavixta** [comment]
Ah, just remove opt=true in module/init.lua 
.For people who want to install Treesitter playground

**Comment by NTBBloodbath** [comment]
Hey, sorry for the late reply, I wasn't at home.

You can also do `after = 'nvim-treesitter'` in your playground setup (at least that's how I setup it).
