### ISSUE TITLE
TrueZen is not loading??

### ISSUE THREAD

**Issue by molleweide** [NTBBloodbath/doom-nvim#74]
Either I don't understand how to load it or it isn't loading 📦 

so this is the keybinding under lua/doom.. and zen is uncommented in doomrc.

```lua
if not functions.is_plugin_disabled('zen') then
	utils.map('n', '<F6>', ':TZAtaraxis<CR>', opts)
end
```

**Comment by NTBBloodbath** [comment]
Hey, I'm finally at home :)

I think that I fixed it in the development branch, was a lazy-loading issue. I'll push the fix to main branch too, I'll let you know when it's done :)

**Comment by NTBBloodbath** [comment]
Hey, should be fine now. If it's not working yet please do `:PackerCompile` and restart Neovim, if it's still not working feel free to re-open this issue :)

**Comment by molleweide** [comment]
cool thanks! 
I'm gonna check out the dev branch also.
