### ISSUE TITLE
Error when trying to update.

### ISSUE THREAD

**Issue by 2m3dz** [NTBBloodbath/doom-nvim#75]
I get this: 
E5108: Error executing lua /home/xroot/.config/nvim/lua/doom/core/functions/init.lua:205: bad argument #1 to 'read' (invalid option)
Any tips to troubleshoot this?

**Comment by NTBBloodbath** [comment]
Hey, sorry for the late reply.

I think that's a dup of #51 but we have already discovered the fix for it so gimme a few moments to push them. After it just update manualyl using `git pull` in your doom-nvim directory :)

**Comment by NTBBloodbath** [comment]
Should be fixed now, please update manually and let me know if the issue persist!

**Comment by 2m3dz** [comment]
> Should be fixed now, please update manually and let me know if the issue persist!

Working like a charm! 
Thank you for keeping it blazing fast xD
