### ISSUE TITLE
mapping problem with commandline and search /

### ISSUE THREAD

**Issue by molleweide** [NTBBloodbath/doom-nvim#76]
Hi again,

I try this binding
```
	    {'n', ';', ':'},
```

and it does work but the command line is not being shown upon pressing `;` now.

1.        press `;`     ->    shows nothing
2.        press `h`     ->    shows `:h`

so the command works but it just doesn't show on the first key press / or initial `;`.

Does this only happen to me?

And it is the same with `/` search commands also.
If I press `/` nothing shows but I know that the command works under the hood.

**Comment by NTBBloodbath** [comment]
Hey, that's because Doom sets the `silent` option for the mappings, maybe we should make it optional :)

**Comment by molleweide** [comment]
Aaha that makes sense then

**Comment by molleweide** [comment]
is can i pass a fourth arg table with silent=false?

**Comment by NTBBloodbath** [comment]
Hi, you will need to do it yourself at the moment, but I'll implement it in a very near future!

You will need to modify this [lua/doom/core/functions/init.lua](https://github.com/NTBBloodbath/doom-nvim/blob/main/lua/doom/core/functions/init.lua#L66-L71) block a bit, basically removing the `opts` variable and doing a conditional assignment. So it should look like this:

```lua
elseif scope == 'mappings' then
	for _, map in ipairs(settings_tbl) do
		-- scope, lhs, rhs, options
		utils.map(map[1], map[2], map[3], map[4] and map[4] or {})
	end
```

and you will be able to pass your custom options for your mappings.

Side note: the `map()` function automatically sets the `noremap` argument _and that's gonna be changed in the future too if needed_.

**Comment by molleweide** [comment]
> Hey, that's because Doom sets the `silent` option for the mappings, maybe we should make it optional :)

yes I think that would be a great idea. another example that doesn't work also is for using the 'map' keyword
instead of 'n' or 'v'.

> Hi, you will need to do it yourself at the moment, but I'll implement it in a very near future!
> 
> You will need to modify this [lua/doom/core/functions/init.lua](https://github.com/NTBBloodbath/doom-nvim/blob/main/lua/doom/core/functions/init.lua#L66-L71) block a bit, basically removing the `opts` variable and doing a conditional assignment. So it should look like this:
> 
> ```lua
> elseif scope == 'mappings' then
> 	for _, map in ipairs(settings_tbl) do
> 		-- scope, lhs, rhs, options
> 		utils.map(map[1], map[2], map[3], map[4] and map[4] or {})
> 	end
> ```
> 
> and you will be able to pass your custom options for your mappings (see `:h map-arguments` and `:h nvim_set_keymap()` to know the valid options).
> 
> Side note: the `map()` function automatically sets the `noremap` argument _and that's gonna be changed in the future too if needed_.

Thanks man for the direction! I will try to get it to work. brb!!

**Comment by NTBBloodbath** [comment]
> > Hey, that's because Doom sets the `silent` option for the mappings, maybe we should make it optional :)
> 
> yes I think that would be a great idea. another example that doesn't work also is for using the 'map' keyword
> instead of 'n' or 'v'.

Do you mean `nmap` and these stuff? If that's the case then it's not possible, the Lua api for the keybindings only takes the keybind mode and if the `noremap` option was not passed then the mapping is automatically set to `<mode>map`. You can take a look at `:h nvim_set_keymap()`.

> > Hi, you will need to do it yourself at the moment, but I'll implement it in a very near future!
> > You will need to modify this [lua/doom/core/functions/init.lua](https://github.com/NTBBloodbath/doom-nvim/blob/main/lua/doom/core/functions/init.lua?rgh-link-date=2021-07-29T18%3A46%3A17Z#L66-L71) block a bit, basically removing the `opts` variable and doing a conditional assignment. So it should look like this:
> > ```lua
> > elseif scope == 'mappings' then
> > 	for _, map in ipairs(settings_tbl) do
> > 		-- scope, lhs, rhs, options
> > 		utils.map(map[1], map[2], map[3], map[4] and map[4] or {})
> > 	end
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and you will be able to pass your custom options for your mappings (see `:h map-arguments` and `:h nvim_set_keymap()` to know the valid options).
> > Side note: the `map()` function automatically sets the `noremap` argument _and that's gonna be changed in the future too if needed_.
> 
> Thanks man for the direction! I will try to get it to work. brb!!

No problem, glad to help. Hope it works for you! :)

**Comment by molleweide** [comment]
Allright cool I am going to read the nvim api docs and make sure i understand.

**Comment by molleweide** [comment]
hey are you thinking about including `nvim-mapper` into doom for key mappings?

**Comment by NTBBloodbath** [comment]
@molleweide Hey, yeah and it's already implemented in the development branch :)

**Comment by molleweide** [comment]
very nice! i have to check out the develp branch.

**Comment by NTBBloodbath** [comment]
I'll be closing this because the feature was already implemented in the development version so I can have a better track of the next version milestone :slightly_smiling_face:
