### ISSUE TITLE
bad first impressions

### ISSUE THREAD

**Issue by thugcee** [NTBBloodbath/doom-nvim#77]
Hi,
as many others now, I'm migrating from `init.vim` to `init.lua`. When greping through the Internet I came across on _doom-nvim_. It's design guides looked very interesting so I proceeded to the Install section. Here is what have made me concern:
- Installation manual mentions only one way to install doom_nvim: executing a shell script downloaded from the Internet.
- This shell script doesn't respect `XDG_CONFIG_HOME` nor ` XDG_CONFIG_DIRS`.
- For no reason it installs some font and not inform an user about where it was installed.
- For no reason on Darwin it copies $HOME/.local/share/fonts/* to $HOME/Library/Fonts/.
- It doesn't uninstall this font when _uninstall_ function is executed.
- Function named `backup_neovim` actually installs _doom_nvim_.
- In lines 151,152 the install script first creates a directory and then links something from inside of this directory.
- It verifies only an existence of `nvim` command but not the version 0.5, which is required.
- It says that it needs`node` and `npm` which are  optional.
- Actual _doom_nvim_ Lua code doesn't respect `XDG_CONFIG_HOME` either.

Those are small things but finding them makes me wonder if I have to read all _doom_nvim_ code and verify it's behaviour.

**Comment by NTBBloodbath** [comment]
Hey, thank you so much for such detailed feedback, I really appreciate it!

Now I think that our installer _and installation guide_ needs some refacts and improvements and that's a really good sign because it indicates that the code quality isn't the best right now in BASH.

> This shell script doesn't respect XDG_CONFIG_HOME nor XDG_CONFIG_DIRS.

Hmm that's a great point, we should respect them, they're here for a reason. However there can be some systems where `XDG_CONFIG_HOME` is not defined (that's my case in Fedora, had to set it manually) and if that's the case then I think we can fallback to `~/.config/`.

> For no reason it installs some font and not inform an user about where it was installed.

We should be a bit more verbose then, these are things that the user needs to know.

> For no reason on Darwin it copies $HOME/.local/share/fonts/* to $HOME/Library/Fonts/.

Are you a Darwin user, right? I never used a mac before so it can be really dirty. Do you recommend to install the font directly to `$HOME/Library/Fonts/`? It makes more sense for me, but want to know what do you think about.

---

I would love to answer all the points but I don't have to write a bible here haha, I'll definitely start working on it this weekend, it's really needed and as the people says, "The first impression is everything". Again, thank you for this.

Regards :slightly_smiling_face:

**Comment by thugcee** [comment]
> Hey, thank you so much for such detailed feedback, I really appreciate it!
> 
> Now I think that our installer _and installation guide_ needs some refacts and improvements and that's a really good sign because it indicates that the code quality isn't the best right now in BASH.
> 
> > This shell script doesn't respect XDG_CONFIG_HOME nor XDG_CONFIG_DIRS.
> 
> Hmm that's a great point, we should respect them, they're here for a reason. However there can be some systems where `XDG_CONFIG_HOME` is not defined (that's my case in Fedora, had to set it manually) and if that's the case then I think we can fallback to `~/.config/`.

Neovim respects them and people use it to switch configurations or test new ones like doom-nvim - that was me :)
Simple `BASE="${XDG_CONFIG_HOME:-$HOME/.config/}"` should do.

> > For no reason it installs some font and not inform an user about where it was installed.
> 
> We should be a bit more verbose then, these are things that the user needs to know.

I can understand that you install this font to get working Nerd icons, but the second postulate is "_Your system, your rules_". I don't use GUI version of Neovim and my terminal has configured Nerd font I like the most. Moreover in popular Linux distributions user fonts are stored in `~/.fonts` by default. IMHO you should ask whether to install this font or not, or display a _curl_ command doing it, so a user can paste it and install themself if one wants to.

> > For no reason on Darwin it copies $HOME/.local/share/fonts/* to $HOME/Library/Fonts/.
> 
> Are you a Darwin user, right? I never used a mac before so it can be really dirty. Do you recommend to install the font directly to `$HOME/Library/Fonts/`? It makes more sense for me, but want to know what do you think about.

I'm a Linux user. I just thought that in `$HOME/.local/share/fonts/` can be stuff someone doesn't want to have in `$HOME/Library/Fonts/`. Copy just what you need, if you have to, not whole directory.

> I would love to answer all the points but I don't want to write a bible here haha, I'll definitely start working on it this weekend, it's really needed and as the people says, "The first impression is everything". Again, thank you for this.

Three simple commands are enough to install _doom-nvim_, why do you bother yourself with installation script? :)

**Comment by NTBBloodbath** [comment]
Hi, I think that you're right with the last sentence and as you've said one of our mantras is "_Your system, your rules_" so things like fonts can be directly installed by the users if they need to.

I think I'm gonna delete the installation script, now I see it as a useless stuff. We'll have less stuff to maintain and the user will have a complete control over doom's installation IMO

**Comment by thugcee** [comment]
Thank you for super fast response. I've switched to _develop_ branch and tried:
```
XDG_CONFIG_HOME=~/.config/config-doom-nvim/ XDG_DATA_HOME=~/.local/share-doom-nvim nvim
```
This gave my a lot of cryptic errors. But after `rm ./nvim/plugin/packer_compiled.lua` doom-nvim started fine and it looks as everything works :)
