### ISSUE TITLE
Error as soon as i install doom nvim

### ISSUE THREAD

**Issue by KittyBorgX** [NTBBloodbath/doom-nvim#78]
![image](https://user-images.githubusercontent.com/82328083/127761832-c88265e7-8269-485c-97d1-d2bea2b26dcb.png)

I tried : 
- PackerSync
- PackerInstall
- PackerCompile

Nothin worked

**Comment by NTBBloodbath** [comment]
Hey, I will need more information here, please take a look at [Reporting issues](https://github.com/NTBBloodbath/doom-nvim/blob/main/docs/contributing.md#reporting-issues), there are some tips :)
