### ISSUE TITLE
jsx/tsx support when enabling javascript/typescript?

### ISSUE THREAD

**Issue by starptr** [NTBBloodbath/doom-nvim#84]
The javascript/typescript language options in `doomrc.lua` doesn't seem to include jsx/tsx (I had to `:TSInstall tsx` manually and lsp completions aren't enabled). It might make sense to include them, since I believe the language server used for javascript/typescript also supports jsx/tsx

**Comment by NTBBloodbath** [comment]
Hey, I think the JSX treesitter queries comes with the JavaScript treesitter parser so we will only need to install TSX with the TypeScript one.

Also the lsp stuff is a bit weird for me, our tsserver setup (we're using the defaults for it) reads all the following filetypes so it should work
- javascript
- javascriptreact
- javascript.jsx
- typescript
- typescriptreact
- typescript.tsx

Have you installed tsserver with `:LspInstall` or used the `+lsp` flag in the `typescript` field in your `doomrc.lua`?

Regards

**Comment by starptr** [comment]
Hm yeah in my `doomrc.lua` I have the `+lsp` flag for the typescript field, so I'm not sure why completions aren't working :(. I did notice that the filetype in the doom statusline says `Typescriptreact` with a capital T, but I assume that's a stylistic thing; running `:set filetype` shows that the filetype is `typescriptreact`

**Comment by NTBBloodbath** [comment]
Hmm I never used JSX/TSX before tbh, I'll need to try it out :thinking:

What does the `:LspInfo` command says when you run it over a JSX/TSX file?

> I did notice that the filetype in the doom statusline says `Typescriptreact` with a capital T, but I assume that's a stylistic thing

Yeah, it's just for styling the statusline :)

**Comment by starptr** [comment]
This is the output on the floating window :(
```
Configured servers: 
Neovim logs at: /home/yuto/.cache/nvim/lsp.log

0 client(s) attached to this buffer: 

0 active client(s): 

Clients that match the filetype typescriptreact:
```

**Comment by NTBBloodbath** [comment]
This is really weird, but there are no clients that matches the filetype? It works for me, haven't changed anything related to lsp.

![image](https://user-images.githubusercontent.com/36456999/128441717-a07f11be-db41-4d09-8dcc-a239ef2c0bf6.png)

Also if it's a new file you will need to save it with `:w` and the lsp should start working _if there's a client that matches the `typescriptreact` filetype_

**Comment by starptr** [comment]
Yeah hm that's really strange, my buffer is a file on disk (and I frequently `:w`) and it doesn't start the LSP. Just to make sure, all I should have needed to do is to comment out & add `typescript +lsp` in `doomrc.lua` and then restart neovim right?

**Comment by NTBBloodbath** [comment]
that's right and if you're in the main branch then you can also add a new entry with `'tsx'` after the typescript one so the treesitter will maintain the tsx parser up-to-date

**Comment by starptr** [comment]
I uninstalled & reinstalled doom & used the vanilla configs except for the 3 line change in `doomrc.lua` where I made it
```lua
		'javascript +lsp',  -- JavaScript support
		'typescript +lsp',  -- TypeScript support
		'tsx',
```
and `:LspInfo` still doesn't show anything in my tsx file :(((. One thing I noticed is that only using the uninstall & reinstall doom scripts isn't enough for a clean install; I had to remove `~/.local/share/nvim` first.

I also uninstalled & reinstalled the dev branch with the same result. If you have any ideas for debugging this lmk, I'm out of ideas hah
