### ISSUE TITLE
develop | `<leader>dl` is required for command to take effect

### ISSUE THREAD

**Issue by molleweide** [NTBBloodbath/doom-nvim#89]
i need to run <leader>dl to reload custom config in order to be able to use command such as:

```
    -- this is disabled in the core
	  {"n", "<c-z>", "<c-z>", opts},
	  {"v", "<c-z>", "<esc><c-z>", opts},
```

at first i was about to add this to core but then i saw you had explicitly disabled this feature LOL

**Comment by NTBBloodbath** [comment]
Ah yes, some personal junk. Maybe we can make the suspending optional like the macros? Obviously not everyone will use this, but there's people that will so making this an option is a good approach IMO

Let me know what do you think about :)

**Comment by molleweide** [comment]
Personally I am used to jumping in and out with susp but it might be a bad pattern i dunno.
We could fix it in the core, but it would be better if one didn't need to reload the doom_config.lua
keymappins every time instead. I mean, I literally have to run <leader>dl every time I want to use some
of my personal mappings and is that how it is supposed to be?

**Comment by NTBBloodbath** [comment]
I have introduced an autocommand that automatically reloads the custom settings (mappings, variables, etc) when modifying the `doom_config.lua` file so it shouldn't be necessary (I think it doesn't work well with `<c-z>` because it's disabled in core)

**Comment by molleweide** [comment]
allright, but in the end, it would make sense to move the suspend command to the leader keys somehow.
i will fix this!!! because you are right. it is annoying when you accidentally jump out.

**Comment by molleweide** [comment]
also, i am writing everything with doom in the browser now LOLOL

**Comment by NTBBloodbath** [comment]
Pretty pog, I want to do it too! lol
