### ISSUE TITLE
develop | which key not displaying hints for ' and `

### ISSUE THREAD

**Issue by molleweide** [NTBBloodbath/doom-nvim#93]
Which key has stopped displaying the available options for ' and ` I have noticed.

Is this only me experiencing this?

**Comment by NTBBloodbath** [comment]
Do you mean when opening Which-Key with the space key? If not, Which-Key had some changes a few days ago as I remember, don't know if they changed something :thinking:

**Comment by molleweide** [comment]
No, not with leader key, I mean when pressing `, which-key (a couple of days ago if I recall) showed a guide to all marks and this was quite amazing. 

Now, nothingh appens for me, and I dunno if this is because I jumped to develop branch and forgot or some update as you seem be refering to :wondering

**Comment by molleweide** [comment]
ofc this was because marks was set to false in module...
