### ISSUE TITLE
Feature request: hot reload plugins setup changes in doom-*** files

### ISSUE THREAD

**Issue by molleweide** [NTBBloodbath/doom-nvim#96]
Yoeddi!

As the title says how do I make module changes and other core stuff take effect without having
to restart nvim?

**Comment by NTBBloodbath** [comment]
Hey, I think that we will need to do a bit of black magic with the modules for reloading them. We can do something similar to [nvim-reload](https://github.com/famiu/nvim-reload).

Basically this plugin unloads the lua modules and loads them again, it's not very hard so I think we can implement this without suffering in the attempt lol
