### ISSUE TITLE
Backup / Undofile does not work

### ISSUE THREAD

**Issue by aperum** [NTBBloodbath/doom-nvim#99]
**Description**
Setting backup = true does not work as intended.

When setting backup = true for the first time, the undo_dir is created but not set inside neovim and undofile is set.
After first start:
```
  :set undofile?
  undofile

  :set undodir?
  undodir=~/.local/share/nvim/undo

```
All starts after that:
```
  :set undofile?
  noundofile

  :set undodir?
  undodir=~/.local/share/nvim/undo
```

On a side note: .local/share/nvim/undodir seems to make more sense than .config/nvim/undodir.

**Local diff**
[DiffGist](https://gist.github.com/aperum/6b865edcc3937eac7bce996344bc16b6)

**Comment by NTBBloodbath** [comment]
Hey, I'm pretty sorry that it was not working as expected and thank you so much for reporting it!

Also thank you for providing that information and a diff, it was really helpful :)

I already fixed the issue locally, I'm gonna push it ASAP

**Comment by NTBBloodbath** [comment]
> On a side note: .local/share/nvim/undodir seems to make more sense than .config/nvim/undodir.

Yeah, now that you said it, it makes a lot more sense, I'll make sure to include this change in the next release.

Regards

**Comment by aperum** [comment]
Thanks for the fast fix and update! 
Just to let you know that after the update, undofile works but still is using the neovim default undodir:

 ```
 :set  undodir?
  undodir=~/.local/share/nvim/undo
```
I don't mind it as i like the location but other users might be surprised.

Grepping through the source i could not find any place vim.opt.undofile gets set so adding it to core/default/init.lua fixes it:

```
diff --git a/lua/doom/core/default/init.lua b/lua/doom/core/default/init.lua
index 725d331..77f819b 100644
--- a/lua/doom/core/default/init.lua
+++ b/lua/doom/core/default/init.lua
@@ -113,6 +113,7 @@ M.load_default_options = function()
                if vim.fn.isdirectory(undo_dir) ~= 1 then
                        vim.api.nvim_command('!mkdir -p ' .. undo_dir)
                end
+               vim.opt.undodir = undo_dir
                vim.opt.undofile = true
        end
```

**Comment by NTBBloodbath** [comment]
@aperum woops, I thought that we had it somewhere.

Thank you so much for finding this, I'll add it ASAP!

Regards

**Comment by NTBBloodbath** [comment]
Should be fixed now, please update :)

**Comment by aperum** [comment]
Works as intended. Thanks!
